In [68]:
import pandas as pd
import numpy as np

# Limpeza de Dados

Dados do *mundo real* raramente são limpos: muitas vezes, para chegar na informação real precisamos penar e sofrer! A limpeza de dados (**data scrubbing** em inglês) é uma habilidade fundamental para qualquer pessoa trabalhando com dados (seja um cientista de dados, um analista de BI ou um engenheiro de dados!). Hoje vamos aprender algumas das técnicas que podemos utilizar para problemas gerais que encontramos em dados.

Vamos começar carregando nossos dados: utilizaremos hoje uma tabela semelhante à `tb_veic`: mas essa nova tabela contém mais informações! Infelizmente, muitas dessas informações estão com problemas, que tentaremos corrigir ao longo da aula hoje.

**Para se aprofundar**: https://www.oreilly.com/library/view/python-data-cleaning/9781800565661/ (*Python Data Cleaning Cookbook* da editora O'Reilly)

In [69]:
tb_veic_messy = pd.read_csv("data/vehicles_messy.csv", dtype={"year": "object"})

/var/folders/c2/4vv1dtt97gl9bn1lvw8rf0k40000gn/T/ipykernel_44873/1565233185.py:1: DtypeWarning: Columns (71,72,73,74,75,77,80,84) have mixed types. Specify dtype option on import or set low_memory=False.
  tb_veic_messy = pd.read_csv("data/vehicles_messy.csv", dtype={"year": "object"})

In [70]:
tb_veic_messy.head()

,Unnamed: 0,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,guzzler,trans_dscr,tCharger,sCharger,atvType,fuelType2,rangeA,evMotor,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb,year_num_errado,mfrCodeDffr
0,0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.0,Rear-Wheel Drive,9011,(FFS),-1,1600,0,Regular,Regular Gasoline,-1,-1,25,0.0,0,0.0,0.0,0.0,0.0,0,0,1,0,0,Alfa Romeo,Spider Veloce 2000,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,23.3333,0.0,35.0000,0.0,Two Seaters,1985,-1250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985a,1
1,1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,12.0,4.9,Rear-Wheel Drive,22020,(GUZZLER),-1,3050,0,Regular,Regular Gasoline,-1,-1,14,0.0,0,0.0,0.0,0.0,0.0,0,0,10,0,0,Ferrari,Testarossa,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,11.0000,0.0,19.0000,0.0,Two Seaters,1985,-8500,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985,1
2,2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,329.148148,27,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,2100,(FFS),-1,1250,0,Regular,Regular Gasoline,-1,-1,33,0.0,0,0.0,0.0,0.0,0.0,19,77,100,0,0,Dodge,Charger,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,29.0000,0.0,47.0000,0.0,Subcompact Cars,1985,500,NaN,SIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985,1
3,3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,8.0,5.2,Rear-Wheel Drive,2850,NaN,-1,3050,0,Regular,Regular Gasoline,-1,-1,12,0.0,0,0.0,0.0,0.0,0.0,0,0,1000,0,0,Dodge,B150/B250 Wagon 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Automatic 3-spd,12.2222,0.0,16.6667,0.0,Vans,1985,-8500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985,1
4,4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,2150,0,Premium,Premium Gasoline,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,10000,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,21.0000,0.0,32.0000,0.0,Compact Cars,1993,-4000,NaN,NaN,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1993,1

In [71]:
tb_veic_messy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37843 entries, 0 to 37842
Data columns (total 86 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       37843 non-null  int64
 1   barrels08        37843 non-null  float64
 2   barrelsA08       37843 non-null  float64
 3   charge120        37843 non-null  float64
 4   charge240        37843 non-null  float64
 5   city08           37843 non-null  int64
 6   city08U          37843 non-null  float64
 7   cityA08          37843 non-null  int64
 8   cityA08U         37843 non-null  float64
 9   cityCD           37843 non-null  float64
 10  cityE            37843 non-null  float64
 11  cityUF           37843 non-null  float64
 12  co2              37843 non-null  int64
 13  co2A             37843 non-null  int64
 14  co2TailpipeAGpm  37843 non-null  float64
 15  co2TailpipeGpm   37843 non-null  float64
 16  comb08           37843 non-null  int64
 17  comb08U          37843 non-null  float64
 18  combA08          37843 non-null  int64
 19  combA08U         37843 non-null  float64
 20  combE            37843 non-null  float64
 21  combinedCD       37843 non-null  float64
 22  combinedUF       37843 non-null  float64
 23  cylinders        37720 non-null  float64
 24  displ            37723 non-null  float64
 25  drive            36654 non-null  object
 26  engId            37843 non-null  int64
 27  eng_dscr         22440 non-null  object
 28  feScore          37843 non-null  int64
 29  fuelCost08       37843 non-null  int64
 30  fuelCostA08      37843 non-null  int64
 31  fuelType         37843 non-null  object
 32  fuelType1        37843 non-null  object
 33  ghgScore         37843 non-null  int64
 34  ghgScoreA        37843 non-null  int64
 35  highway08        37843 non-null  int64
 36  highway08U       37843 non-null  float64
 37  highwayA08       37843 non-null  int64
 38  highwayA08U      37843 non-null  float64
 39  highwayCD        37843 non-null  float64
 40  highwayE         37843 non-null  float64
 41  highwayUF        37843 non-null  float64
 42  hlv              37843 non-null  int64
 43  hpv              37843 non-null  int64
 44  id               37843 non-null  int64
 45  lv2              37843 non-null  int64
 46  lv4              37843 non-null  int64
 47  make             37843 non-null  object
 48  model            37843 non-null  object
 49  mpgData          37843 non-null  object
 50  phevBlended      37843 non-null  bool
 51  pv2              37843 non-null  int64
 52  pv4              37843 non-null  int64
 53  range            37843 non-null  int64
 54  rangeCity        37843 non-null  float64
 55  rangeCityA       37843 non-null  float64
 56  rangeHwy         37843 non-null  float64
 57  rangeHwyA        37843 non-null  float64
 58  trany            37832 non-null  object
 59  UCity            37843 non-null  float64
 60  UCityA           37843 non-null  float64
 61  UHighway         37843 non-null  float64
 62  UHighwayA        37843 non-null  float64
 63  VClass           37843 non-null  object
 64  year             37843 non-null  object
 65  youSaveSpend     37843 non-null  int64
 66  guzzler          2281 non-null   object
 67  trans_dscr       15047 non-null  object
 68  tCharger         5186 non-null   object
 69  sCharger         666 non-null    object
 70  atvType          3072 non-null   object
 71  fuelType2        1408 non-null   object
 72  rangeA           1403 non-null   object
 73  evMotor          562 non-null    object
 74  mfrCode          7025 non-null   object
 75  c240Dscr         37 non-null     object
 76  charge240b       37843 non-null  float64
 77  c240bDscr        36 non-null     object
 78  createdOn        37843 non-null  object
 79  modifiedOn       37843 non-null  object
 80  startStop        6138 non-null   object
 81  phevCity         37843 non-null  int64
 82  phevHwy          37843 non-null  int64
 83  phevComb         37843 non-null  int64
 84  year_num_errado  37843 non-null  object
 85  mfrCodeDffr      37843 non-null  int64
dtypes: bool(1), float64(32), int64(28), object(25)
memory usage: 24.6+ MB

Como nosso DataFrame é muito longo (muitas colunas) não conseguimos vê-lo completamente através do método `.head()`. Para visualizar todas as colunas precisamos utilizar uma opção da biblioteca Pandas:

In [72]:
pd.set_option('display.max_columns', 500)
tb_veic_messy.head()

,Unnamed: 0,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,guzzler,trans_dscr,tCharger,sCharger,atvType,fuelType2,rangeA,evMotor,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb,year_num_errado,mfrCodeDffr
0,0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.0,Rear-Wheel Drive,9011,(FFS),-1,1600,0,Regular,Regular Gasoline,-1,-1,25,0.0,0,0.0,0.0,0.0,0.0,0,0,1,0,0,Alfa Romeo,Spider Veloce 2000,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,23.3333,0.0,35.0000,0.0,Two Seaters,1985,-1250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985a,1
1,1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,12.0,4.9,Rear-Wheel Drive,22020,(GUZZLER),-1,3050,0,Regular,Regular Gasoline,-1,-1,14,0.0,0,0.0,0.0,0.0,0.0,0,0,10,0,0,Ferrari,Testarossa,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,11.0000,0.0,19.0000,0.0,Two Seaters,1985,-8500,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985,1
2,2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,329.148148,27,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,2100,(FFS),-1,1250,0,Regular,Regular Gasoline,-1,-1,33,0.0,0,0.0,0.0,0.0,0.0,19,77,100,0,0,Dodge,Charger,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,29.0000,0.0,47.0000,0.0,Subcompact Cars,1985,500,NaN,SIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985,1
3,3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,8.0,5.2,Rear-Wheel Drive,2850,NaN,-1,3050,0,Regular,Regular Gasoline,-1,-1,12,0.0,0,0.0,0.0,0.0,0.0,0,0,1000,0,0,Dodge,B150/B250 Wagon 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Automatic 3-spd,12.2222,0.0,16.6667,0.0,Vans,1985,-8500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985,1
4,4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,2150,0,Premium,Premium Gasoline,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,10000,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,21.0000,0.0,32.0000,0.0,Compact Cars,1993,-4000,NaN,NaN,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1993,1

## Data types

Uma das primeiras etapas na limpeza de dados é garantir que as colunas tenham os tipos desejados: colunas numéricas devem ser ints e floats, colunas de data, datetime, strings serem objects... Primeiro vamos ver algumas formas de determinar os tipos de nossas colunas.

### Checando tipos

In [73]:
tb_veic_messy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37843 entries, 0 to 37842
Data columns (total 86 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       37843 non-null  int64
 1   barrels08        37843 non-null  float64
 2   barrelsA08       37843 non-null  float64
 3   charge120        37843 non-null  float64
 4   charge240        37843 non-null  float64
 5   city08           37843 non-null  int64
 6   city08U          37843 non-null  float64
 7   cityA08          37843 non-null  int64
 8   cityA08U         37843 non-null  float64
 9   cityCD           37843 non-null  float64
 10  cityE            37843 non-null  float64
 11  cityUF           37843 non-null  float64
 12  co2              37843 non-null  int64
 13  co2A             37843 non-null  int64
 14  co2TailpipeAGpm  37843 non-null  float64
 15  co2TailpipeGpm   37843 non-null  float64
 16  comb08           37843 non-null  int64
 17  comb08U          37843 non-null  float64
 18  combA08          37843 non-null  int64
 19  combA08U         37843 non-null  float64
 20  combE            37843 non-null  float64
 21  combinedCD       37843 non-null  float64
 22  combinedUF       37843 non-null  float64
 23  cylinders        37720 non-null  float64
 24  displ            37723 non-null  float64
 25  drive            36654 non-null  object
 26  engId            37843 non-null  int64
 27  eng_dscr         22440 non-null  object
 28  feScore          37843 non-null  int64
 29  fuelCost08       37843 non-null  int64
 30  fuelCostA08      37843 non-null  int64
 31  fuelType         37843 non-null  object
 32  fuelType1        37843 non-null  object
 33  ghgScore         37843 non-null  int64
 34  ghgScoreA        37843 non-null  int64
 35  highway08        37843 non-null  int64
 36  highway08U       37843 non-null  float64
 37  highwayA08       37843 non-null  int64
 38  highwayA08U      37843 non-null  float64
 39  highwayCD        37843 non-null  float64
 40  highwayE         37843 non-null  float64
 41  highwayUF        37843 non-null  float64
 42  hlv              37843 non-null  int64
 43  hpv              37843 non-null  int64
 44  id               37843 non-null  int64
 45  lv2              37843 non-null  int64
 46  lv4              37843 non-null  int64
 47  make             37843 non-null  object
 48  model            37843 non-null  object
 49  mpgData          37843 non-null  object
 50  phevBlended      37843 non-null  bool
 51  pv2              37843 non-null  int64
 52  pv4              37843 non-null  int64
 53  range            37843 non-null  int64
 54  rangeCity        37843 non-null  float64
 55  rangeCityA       37843 non-null  float64
 56  rangeHwy         37843 non-null  float64
 57  rangeHwyA        37843 non-null  float64
 58  trany            37832 non-null  object
 59  UCity            37843 non-null  float64
 60  UCityA           37843 non-null  float64
 61  UHighway         37843 non-null  float64
 62  UHighwayA        37843 non-null  float64
 63  VClass           37843 non-null  object
 64  year             37843 non-null  object
 65  youSaveSpend     37843 non-null  int64
 66  guzzler          2281 non-null   object
 67  trans_dscr       15047 non-null  object
 68  tCharger         5186 non-null   object
 69  sCharger         666 non-null    object
 70  atvType          3072 non-null   object
 71  fuelType2        1408 non-null   object
 72  rangeA           1403 non-null   object
 73  evMotor          562 non-null    object
 74  mfrCode          7025 non-null   object
 75  c240Dscr         37 non-null     object
 76  charge240b       37843 non-null  float64
 77  c240bDscr        36 non-null     object
 78  createdOn        37843 non-null  object
 79  modifiedOn       37843 non-null  object
 80  startStop        6138 non-null   object
 81  phevCity         37843 non-null  int64
 82  phevHwy          37843 non-null  int64
 83  phevComb         37843 non-null  int64
 84  year_num_errado  37843 non-null  object
 85  mfrCodeDffr      37843 non-null  int64
dtypes: bool(1), float64(32), int64(28), object(25)
memory usage: 24.6+ MB

In [74]:
tb_veic_messy.dtypes

Unnamed: 0           int64
barrels08          float64
barrelsA08         float64
charge120          float64
charge240          float64
                    ...
phevCity             int64
phevHwy              int64
phevComb             int64
year_num_errado     object
mfrCodeDffr          int64
Length: 86, dtype: object

In [75]:
tb_veic_messy.dtypes.value_counts()

float64    32
int64      28
object     25
bool        1
dtype: int64

Além de acessar os tipos e conta-los, podemos utilizar o método `.select_dtypes()` para filtrar as colunas de um DataFrame de acordo com seu tipo:

In [80]:
tb_veic_messy.select_dtypes(include = 'number')

,Unnamed: 0,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,engId,feScore,fuelCost08,fuelCostA08,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,UCity,UCityA,UHighway,UHighwayA,youSaveSpend,charge240b,phevCity,phevHwy,phevComb,mfrCodeDffr
0,0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.0,9011,-1,1600,0,-1,-1,25,0.0,0,0.0,0.0,0.0,0.0,0,0,1,0,0,0,0,0,0.0,0.0,0.0,0.0,23.3333,0.0,35.0000,0.0,-1250,0.0,0,0,0,1
1,1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,12.0,4.9,22020,-1,3050,0,-1,-1,14,0.0,0,0.0,0.0,0.0,0.0,0,0,10,0,0,0,0,0,0.0,0.0,0.0,0.0,11.0000,0.0,19.0000,0.0,-8500,0.0,0,0,0,1
2,2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,329.148148,27,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,2100,-1,1250,0,-1,-1,33,0.0,0,0.0,0.0,0.0,0.0,19,77,100,0,0,0,0,0,0.0,0.0,0.0,0.0,29.0000,0.0,47.0000,0.0,500,0.0,0,0,0,1
3,3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,8.0,5.2,2850,-1,3050,0,-1,-1,12,0.0,0,0.0,0.0,0.0,0.0,0,0,1000,0,0,0,0,0,0.0,0.0,0.0,0.0,12.2222,0.0,16.6667,0.0,-8500,0.0,0,0,0,1
4,4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,66031,-1,2150,0,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,10000,0,14,0,90,0,0.0,0.0,0.0,0.0,21.0000,0.0,32.0000,0.0,-4000,0.0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37838,37838,14.982273,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,403.954545,22,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,66030,-1,1500,0,-1,-1,26,0.0,0,0.0,0.0,0.0,0.0,0,0,9995,0,14,0,90,0,0.0,0.0,0.0,0.0,24.0000,0.0,37.0000,0.0,-750,0.0,0,0,0,1
37839,37839,14.330870,0.0,0.0,0.0,20,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,386.391304,23,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,66030,-1,1450,0,-1,-1,28,0.0,0,0.0,0.0,0.0,0.0,0,0,9996,0,14,0,90,0,0.0,0.0,0.0,0.0,25.0000,0.0,39.0000,0.0,-500,0.0,0,0,0,1
37840,37840,15.695714,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,66030,-1,1600,0,-1,-1,24,0.0,0,0.0,0.0,0.0,0.0,0,0,9997,0,14,0,90,0,0.0,0.0,0.0,0.0,23.0000,0.0,34.0000,0.0,-1250,0.0,0,0,0,1
37841,37841,15.695714,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,66030,-1,1600,0,-1,-1,24,0.0,0,0.0,0.0,0.0,0.0,0,0,9998,0,14,0,90,0,0.0,0.0,0.0,0.0,23.0000,0.0,34.0000,0.0,-1250,0.0,0,0,0,1
37842,37842,18.311667,0.0,0.0,0.0,16,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,493.722222,18,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,66031,-1,2250,0,-1,-1,21,0.0,0,0.0,0.0,0.0,0.0,0,0,9999,0,14,0,90,0,0.0,0.0,0.0,0.0,20.0000,0.0,29.0000,0.0,-4500,0.0,0,0,0,1

In [81]:
tb_veic_messy.select_dtypes(exclude = 'object')

,Unnamed: 0,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,engId,feScore,fuelCost08,fuelCostA08,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,UCity,UCityA,UHighway,UHighwayA,youSaveSpend,charge240b,phevCity,phevHwy,phevComb,mfrCodeDffr
0,0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.0,9011,-1,1600,0,-1,-1,25,0.0,0,0.0,0.0,0.0,0.0,0,0,1,0,0,False,0,0,0,0.0,0.0,0.0,0.0,23.3333,0.0,35.0000,0.0,-1250,0.0,0,0,0,1
1,1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,12.0,4.9,22020,-1,3050,0,-1,-1,14,0.0,0,0.0,0.0,0.0,0.0,0,0,10,0,0,False,0,0,0,0.0,0.0,0.0,0.0,11.0000,0.0,19.0000,0.0,-8500,0.0,0,0,0,1
2,2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,329.148148,27,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,2100,-1,1250,0,-1,-1,33,0.0,0,0.0,0.0,0.0,0.0,19,77,100,0,0,False,0,0,0,0.0,0.0,0.0,0.0,29.0000,0.0,47.0000,0.0,500,0.0,0,0,0,1
3,3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,8.0,5.2,2850,-1,3050,0,-1,-1,12,0.0,0,0.0,0.0,0.0,0.0,0,0,1000,0,0,False,0,0,0,0.0,0.0,0.0,0.0,12.2222,0.0,16.6667,0.0,-8500,0.0,0,0,0,1
4,4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,66031,-1,2150,0,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,10000,0,14,False,0,90,0,0.0,0.0,0.0,0.0,21.0000,0.0,32.0000,0.0,-4000,0.0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37838,37838,14.982273,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,403.954545,22,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,66030,-1,1500,0,-1,-1,26,0.0,0,0.0,0.0,0.0,0.0,0,0,9995,0,14,False,0,90,0,0.0,0.0,0.0,0.0,24.0000,0.0,37.0000,0.0,-750,0.0,0,0,0,1
37839,37839,14.330870,0.0,0.0,0.0,20,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,386.391304,23,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,66030,-1,1450,0,-1,-1,28,0.0,0,0.0,0.0,0.0,0.0,0,0,9996,0,14,False,0,90,0,0.0,0.0,0.0,0.0,25.0000,0.0,39.0000,0.0,-500,0.0,0,0,0,1
37840,37840,15.695714,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,66030,-1,1600,0,-1,-1,24,0.0,0,0.0,0.0,0.0,0.0,0,0,9997,0,14,False,0,90,0,0.0,0.0,0.0,0.0,23.0000,0.0,34.0000,0.0,-1250,0.0,0,0,0,1
37841,37841,15.695714,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,66030,-1,1600,0,-1,-1,24,0.0,0,0.0,0.0,0.0,0.0,0,0,9998,0,14,False,0,90,0,0.0,0.0,0.0,0.0,23.0000,0.0,34.0000,0.0,-1250,0.0,0,0,0,1
37842,37842,18.311667,0.0,0.0,0.0,16,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,493.722222,18,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,66031,-1,2250,0,-1,-1,21,0.0,0,0.0,0.0,0.0,0.0,0,0,9999,0,14,False,0,90,0,0.0,0.0,0.0,0.0,20.0000,0.0,29.0000,0.0,-4500,0.0,0,0,0,1

In [84]:
tb_veic_num = tb_veic_messy.select_dtypes(exclude = 'object')
tb_veic_num.describe()

,Unnamed: 0,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,engId,feScore,fuelCost08,fuelCostA08,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,UCity,UCityA,UHighway,UHighwayA,youSaveSpend,charge240b,phevCity,phevHwy,phevComb,mfrCodeDffr
count,37843.000000,37843.000000,37843.000000,37843.0,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37720.000000,37723.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.00000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.0
mean,18921.000000,17.532506,0.216169,0.0,0.023531,17.941389,4.042737,0.520149,0.327163,0.000406,0.184790,0.000706,61.503713,5.349919,17.771433,473.179736,20.195809,4.549751,0.581191,0.359027,0.190575,0.000335,0.000691,5.737990,3.318180,8860.308961,-0.035145,1882.060090,79.070105,-0.037206,-0.929630,24.104881,5.438467,0.686891,0.418698,0.000233,0.198247,0.000673,2.026214,10.424332,19019.286235,1.849219,6.165658,13.696113,33.769125,0.392675,0.352618,0.03680,0.343399,0.033475,22.587229,0.652380,33.619221,0.933845,-2658.999022,0.004360,0.069313,0.068203,0.068573,1.0
std,10924.477455,4.575950,1.141527,0.0,0.427647,6.660360,9.645820,3.837874,3.542596,0.039918,2.904558,0.019458,153.387715,55.539497,94.129283,122.188847,6.623444,10.389994,3.966255,3.589260,2.979567,0.035284,0.019049,1.751795,1.361399,17829.683477,2.379584,510.280408,417.668580,2.374338,0.627565,6.963192,11.936327,4.308934,3.808877,0.029564,3.091862,0.018583,5.947989,28.148770,11034.784855,4.429983,9.743297,31.269930,45.914462,8.251191,8.049082,1.15827,8.171939,1.032642,9.350163,5.284547,10.048326,6.059456,2553.098329,0.142776,1.966806,1.871986,1.913647,0.0
min,0.000000,0.060000,0.000000,0.0,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,0.000000,0.000000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,-1.000000,550.000000,0.000000,-1.000000,-1.000000,9.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-22250.000000,0.000000,0.000000,0.000000,0.000000,1.0
25%,9460.500000,14.330870,0.000000,0.0,0.000000,15.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,0.000000,388.000000,17.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2.200000,0.000000,-1.000000,1500.000000,0.000000,-1.000000,-1.000000,20.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9461.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,18.000000,0.000000,27.100000,0.000000,-4250.000000,0.000000,0.000000,0.000000,0.000000,1.0
50%,18921.000000,17.347895,0.000000,0.0,0.000000,17.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,0.000000,467.736842,19.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,3.000000,211.000000,-1.000000,1850.000000,0.000000,-1.000000,-1.000000,24.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18923.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,21.000000,0.000000,33.000000,0.000000,-2500.000000,0.000000,0.000000,0.000000,0.000000,1.0
75%,28381.500000,20.600625,0.000000,0.0,0.000000,20.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,0.000000,555.437500,23.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,4.300000,4505.000000,-1.000000,2200.000000,0.000000,-1.000000,-1.000000,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,28570.500000,0.000000,13.000000,0.000000,91.000000,0.000000,0.000000,0.00000,0.000000,0.000000,25.139300,0.000000,38.109600,0.000000,-750.000000,0.000000,0.000000,0.000000,0.000000,1.0
max,37842.000000,47.087143,18.311667,0.0,12.000000,138.000000,138.304000,127.000000,127.093000,5.350000,122.000000,0.849000,847.000000,719.000000,719.000000,1269.571429,124.000000,124.360100,117.000000,116.936400,121.000000,4.800000,0.834000,16.000000,8.400000,69102.000000,10.000000,5800.000000,3800.000000,10.000000,8.000000,111.000000,111.370000,107.000000,106.531000,4.060000,120.000000,0.813000,49.000000,195.000000,38173.000000,41.000000,55.000000,194.000000,192.000000,315.000000,305.900000,77.50400,346.900000,65.632000,197.577100,181.560900,159.100000,152.187800,4000.000000,7.000000,97.000000,79.000000,88.000000,1.0

In [88]:
tb_veic_str = tb_veic_messy.select_dtypes(include = ['object'])
tb_veic_str.describe()

,drive,eng_dscr,fuelType,fuelType1,make,model,mpgData,trany,VClass,year,guzzler,trans_dscr,tCharger,sCharger,atvType,fuelType2,rangeA,evMotor,mfrCode,c240Dscr,c240bDscr,createdOn,modifiedOn,startStop,year_num_errado
count,36654,22440,37843,37843,37843,37843,37843,37832,37843,37843,2281,15047,5186,666,3072,1408,1403,562,7025,37,36,37843,37843,6138,37843
unique,8,541,14,6,133,3692,2,46,34,34,3,52,1,1,8,4,157,110,45,5,4,145,129,2,47
top,Front-Wheel Drive,(FFS),Regular,Regular Gasoline,Chevrolet,F150 Pickup 2WD,N,Automatic 4-spd,Compact Cars,1984,G,CLKUP,T,S,FFV,E85,310,288V Ni-MH,GMX,standard charger,80 amp dual charger,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,N,1984
freq,13286,8827,25076,26326,3795,207,26605,11042,5495,1964,1302,7809,5186,666,1325,1325,117,114,1061,28,28,34220,32276,4462,1964

### Convertendo tipos `.astype()`

Nas colunas acima podemos ver que a coluna `year` parece conter apenas números (o que faria sentido) mas está carregada com um `object` (o que não faz tanto sentido). Vamos investigar os dados dessa colunas para entendermos melhor o que ela contém:

In [89]:
tb_veic_messy['year'].head(20)

0     1985
1     1985
2     1985
3     1985
4     1993
5     1993
6     1993
7     1993
8     1993
9     1993
10    1993
11    1993
12    1993
13    1993
14    1985
15    1993
16    1993
17    1993
18    1993
19    1993
Name: year, dtype: object

In [90]:
tb_veic_messy['year'].describe()

count     37843
unique       34
top        1984
freq       1964
Name: year, dtype: object

In [91]:
tb_veic_messy['year'].unique()

array(['1985', '1993', '1994', '1995', '1996', '1997', '1998', '1999',
       '2000', '2001', '1986', '2002', '2003', '2004', '2005', '2006',
       '2007', '2008', '2009', '2010', '1984', '1987', '1988', '1989',
       '1990', '1991', '1992', '2011', '2012', '2013', '2014', '2015',
       '2016', '2017'], dtype=object)

In [92]:
tb_veic_messy['year'].value_counts()

1984    1964
1985    1701
2015    1283
2016    1258
1987    1247
2014    1226
1986    1210
2008    1187
2013    1185
2009    1184
2005    1166
2012    1153
1989    1153
1991    1132
1988    1130
2011    1130
2007    1126
2004    1122
1992    1121
2010    1109
2006    1104
1993    1093
1990    1078
2003    1044
1994     982
2002     975
1995     967
2001     911
2017     863
1999     852
2000     840
1998     812
1996     773
1997     762
Name: year, dtype: int64

Aparentemente a colunas contém apenas números. Neste caso, podemos utilizar o método `.astype()` para converte-la em um tipo numérico:

In [93]:
tb_veic_messy['year'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 37843 entries, 0 to 37842
Series name: year
Non-Null Count  Dtype
--------------  -----
37843 non-null  object
dtypes: object(1)
memory usage: 295.8+ KB

In [94]:
tb_veic_messy['year'].astype('int64')

0        1985
1        1985
2        1985
3        1985
4        1993
         ...
37838    1993
37839    1993
37840    1993
37841    1993
37842    1993
Name: year, Length: 37843, dtype: int64

In [95]:
tb_veic_messy['year_num'] = tb_veic_messy['year'].astype('int64')

In [97]:
tb_veic_messy[['year', 'year_num']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37843 entries, 0 to 37842
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   year      37843 non-null  object
 1   year_num  37843 non-null  int64
dtypes: int64(1), object(1)
memory usage: 591.4+ KB

In [98]:
tb_veic_messy[['year', 'year_num']].head()

   year  year_num
0  1985      1985
1  1985      1985
2  1985      1985
3  1985      1985
4  1993      1993

In [99]:
tb_veic_messy['year_num'].astype('str')

0        1985
1        1985
2        1985
3        1985
4        1993
         ...
37838    1993
37839    1993
37840    1993
37841    1993
37842    1993
Name: year_num, Length: 37843, dtype: object

### Convertendo Tipos com `.map()`

Além do método `.astype()`, podemos utilizar o método `.map()` para converter o tipo de uma coluna. O método `.map()` **mapea uma função sobre os elementos de uma coluna**, ou seja, ele retorna uma nova coluna, do tamanho da coluna original, preenchido com o resultado da função sobre os elementos da coluna original (um pouco parecido com os List Comprehensions...).

Vamos utilizar este método para aplicar a função `int` aos elementos da coluna `year`:

In [102]:
tb_veic_messy['year'].head()

0    1985
1    1985
2    1985
3    1985
4    1993
Name: year, dtype: object

In [103]:
tb_veic_messy['year'].map(int)

0        1985
1        1985
2        1985
3        1985
4        1993
         ...
37838    1993
37839    1993
37840    1993
37841    1993
37842    1993
Name: year, Length: 37843, dtype: int64

Porque usar o `.map()`? Em muitas situações, o problema em nossos dados não será apenas de definição de tipo e algumas linhas da nossa coluna numérica terão strings misturados... Neste caso o método `.astype()` não funcionará:

In [104]:
tb_veic_messy['year_num_errado'].unique()

array(['1985a', '1985', '1993', '1994', '1995', '1996', '1997', '1998',
       '1999', '2000', '2001', '1986', '2002', 2002, 1986, 1985, 2003,
       2004, 2005, 1999, 2006, 2007, 2008, 1995, 1996, 2009, 2010, 1984,
       1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1997, 1998, 2000,
       2001, 2011, 2012, 2013, 2014, 2015, 2016, 2017], dtype=object)

In [105]:
tb_veic_messy['year_num_errado'].value_counts()

1984     1964
2015     1283
2016     1258
1987     1247
2014     1226
2008     1187
2013     1185
2009     1184
2005     1166
1986     1161
2012     1153
1989     1153
1991     1132
1988     1130
2011     1130
2007     1126
2004     1122
1992     1121
2010     1109
2006     1104
1990     1078
2003     1044
1994      963
2002      935
1985      929
1995      927
2001      907
2017      863
2000      836
1998      806
1999      799
1985      771
1996      749
1997      727
1993      617
1993      476
1999       53
1986       49
1995       40
2002       40
1997       35
1996       24
1994       19
1998        6
2001        4
2000        4
1985a       1
Name: year_num_errado, dtype: int64

In [106]:
tb_veic_messy['year_num_errado'].astype('int64')

ValueError: invalid literal for int() with base 10: '1985a'

In [107]:
int('1985a')

ValueError: invalid literal for int() with base 10: '1985a'

Passar a função `int` através do `.map()` também não funcionará!

In [108]:
tb_veic_messy['year_num_errado'].map(int)

ValueError: invalid literal for int() with base 10: '1985a'

Mas o método `.map()` nos permite passar **QUALQUER FUNÇÃO** para sobre coluna! Vamos definir uma função que tenta converter um string em número mas que, ao invés de falhar com strings, retorna `np.nan`:

In [109]:
def te_int(value):
    try:
        return int(value)
    except ValueError as e:
        return np.nan

In [111]:
te_int('1985a')

nan

In [113]:
tb_veic_messy['year_num_errado']

0        1985a
1         1985
2         1985
3         1985
4         1993
         ...
37838     1993
37839     1993
37840     1993
37841     1993
37842     1993
Name: year_num_errado, Length: 37843, dtype: object

In [112]:
tb_veic_messy['year_num_errado'].map(te_int)

0           NaN
1        1985.0
2        1985.0
3        1985.0
4        1993.0
          ...
37838    1993.0
37839    1993.0
37840    1993.0
37841    1993.0
37842    1993.0
Name: year_num_errado, Length: 37843, dtype: float64

In [114]:
tb_veic_messy['year_map'] = tb_veic_messy['year_num_errado'].map(te_int)
tb_veic_messy[['year_num_errado', 'year_map']].head()

  year_num_errado  year_map
0           1985a       NaN
1            1985    1985.0
2            1985    1985.0
3            1985    1985.0
4            1993    1993.0

Quando verificamos os valores da coluna `year_num_errado` vimos que alguns anos estavam com um caráctere extra (a letra `a`). Com a função que definimos acima, nossa nova coluna de inteiros não terá nenhum valor nessas linhas. Como podemos alterar nossa função para que ela limpe, não remova, as linhas com `strings` misturados?

In [131]:
import re
def limpar_numero(value):
    pattern = "[^0-9]"
    value_novo = re.sub(pattern, '', str(value))
    return float(value_novo)

In [132]:
limpar_numero('195a')

195.0

In [133]:
tb_veic_messy['year_num_errado'].map(limpar_numero)

0        1985.0
1        1985.0
2        1985.0
3        1985.0
4        1993.0
          ...
37838    1993.0
37839    1993.0
37840    1993.0
37841    1993.0
37842    1993.0
Name: year_num_errado, Length: 37843, dtype: float64

In [134]:
limpar_numero('11-97300-1365')

11973001365.0

In [135]:
lista_str = [str(i) for i in range(10)]
lista_str

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [136]:
[float(i) for i in lista_str]

[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]

In [137]:
lista_nova = []
for numero in lista_str:
    novo_numero = float(numero)
    lista_nova.append(novo_numero)
    
print(lista_str)
print(lista_nova)

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]

In [138]:
[limpar_numero(numero) for numero in lista_str]

[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]

In [139]:
tb_veic_messy['year_num_errado'].map(limpar_numero)

0        1985.0
1        1985.0
2        1985.0
3        1985.0
4        1993.0
          ...
37838    1993.0
37839    1993.0
37840    1993.0
37841    1993.0
37842    1993.0
Name: year_num_errado, Length: 37843, dtype: float64

## Valores ausentes (missing values)

Um dos maiores problemas que vamos enfrentar quando trabalhamos com dados reais são os ***missing values***. Os ***missing values*** surgem de 3 formas:

1. Pela aplicação de funções em nosso código 
    * **Exemplo**: `.map()` que construímos acima;
1. Através de falhas na coleta/armazenagem de dados
    * **Exemplo**: em uma pesquisa física, alguns campos preenchidos estavam ilegíveis.
1. Para representar características reais da observação
    * **Exemplo**: em uma tabela de e-commerce, com o faturamento mês a mês de cada item, a coluna `desconto` pode aparecer como NA para representar produtos que não estavam promocionados

Antes de tratarmos NAs precisamos **ENTENDER** porque eles existem, se é possível (e desejável) tentar recuperar essa informação, se ela pode ser reconstruída a partir de outras colunas, etc...

Começaremos vendo como a biblioteca Pandas representa NAs no Python: o objeto `np.nan`

### `np.nan` - o número que não é número!

Porque ter um tipo específico para NAs? Vamos utilizar o exemplo do `.map()` acima para entedermos essa escolha dos desenvolvedores: quando tentamos aplicar a função `int` sobre nossa coluna uma linha com o valor `1985a` impediu a aplicação da função! Uma linha em 37842! Imagine se NAs fossem `strings`: não consegueríamos aplicar nenhuma função numérica sobre colunas com mesmo só um NA!

In [140]:
type(np.nan)

float

In [141]:
np.nan + 1

nan

In [142]:
tb_veic_messy['year_map'].head()

0       NaN
1    1985.0
2    1985.0
3    1985.0
4    1993.0
Name: year_map, dtype: float64

In [143]:
tb_veic_messy.loc[0, 'year_map'] + 1

nan

In [144]:
tb_veic_messy['year_map'] + 1

0           NaN
1        1986.0
2        1986.0
3        1986.0
4        1994.0
          ...
37838    1994.0
37839    1994.0
37840    1994.0
37841    1994.0
37842    1994.0
Name: year_map, Length: 37843, dtype: float64

Esse comportamento é um pouco diferente quando falamos de funções de agregação:

In [145]:
tb_veic_messy['year_map'].head()

0       NaN
1    1985.0
2    1985.0
3    1985.0
4    1993.0
Name: year_map, dtype: float64

In [146]:
tb_veic_messy['year_map'].mean()

2000.0647957296126

Um cuidado que devemos tomar é que quando utilizamos relação de equivalência com `np.nan`:

In [147]:
1 == 1

True

In [148]:
None == None

True

In [149]:
np.nan == np.nan

False

In [151]:
tb_veic_messy['year_map']

0           NaN
1        1985.0
2        1985.0
3        1985.0
4        1993.0
          ...
37838    1993.0
37839    1993.0
37840    1993.0
37841    1993.0
37842    1993.0
Name: year_map, Length: 37843, dtype: float64

In [150]:
tb_veic_messy['year_map'] != np.nan

0        True
1        True
2        True
3        True
4        True
         ...
37838    True
37839    True
37840    True
37841    True
37842    True
Name: year_map, Length: 37843, dtype: bool

In [152]:
tb_veic_messy[tb_veic_messy['year_map'] != np.nan].head()

,Unnamed: 0,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,guzzler,trans_dscr,tCharger,sCharger,atvType,fuelType2,rangeA,evMotor,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb,year_num_errado,mfrCodeDffr,year_num,year_map
0,0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.0,Rear-Wheel Drive,9011,(FFS),-1,1600,0,Regular,Regular Gasoline,-1,-1,25,0.0,0,0.0,0.0,0.0,0.0,0,0,1,0,0,Alfa Romeo,Spider Veloce 2000,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,23.3333,0.0,35.0000,0.0,Two Seaters,1985,-1250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985a,1,1985,NaN
1,1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,12.0,4.9,Rear-Wheel Drive,22020,(GUZZLER),-1,3050,0,Regular,Regular Gasoline,-1,-1,14,0.0,0,0.0,0.0,0.0,0.0,0,0,10,0,0,Ferrari,Testarossa,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,11.0000,0.0,19.0000,0.0,Two Seaters,1985,-8500,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985,1,1985,1985.0
2,2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,329.148148,27,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,2100,(FFS),-1,1250,0,Regular,Regular Gasoline,-1,-1,33,0.0,0,0.0,0.0,0.0,0.0,19,77,100,0,0,Dodge,Charger,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,29.0000,0.0,47.0000,0.0,Subcompact Cars,1985,500,NaN,SIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985,1,1985,1985.0
3,3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,8.0,5.2,Rear-Wheel Drive,2850,NaN,-1,3050,0,Regular,Regular Gasoline,-1,-1,12,0.0,0,0.0,0.0,0.0,0.0,0,0,1000,0,0,Dodge,B150/B250 Wagon 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Automatic 3-spd,12.2222,0.0,16.6667,0.0,Vans,1985,-8500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985,1,1985,1985.0
4,4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,2150,0,Premium,Premium Gasoline,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,10000,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,21.0000,0.0,32.0000,0.0,Compact Cars,1993,-4000,NaN,NaN,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1993,1,1993,1993.0

### Os métodos `.isna()` e `.notna()`

Como vimos acima, para criar uma máscara representando valores `np.nan` não podemos utilizar uma relação de equivalência. Precisamos utilizar os métodos `.isna()` e `.notna()`!

In [153]:
tb_veic_messy['displ'].head()

0    2.0
1    4.9
2    2.2
3    5.2
4    2.2
Name: displ, dtype: float64

In [154]:
tb_veic_messy['displ'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 37843 entries, 0 to 37842
Series name: displ
Non-Null Count  Dtype
--------------  -----
37723 non-null  float64
dtypes: float64(1)
memory usage: 295.8 KB

O método `.isna()` (das `Series`) cria uma máscara que é `True` quando a série tem um valor NA e `False` caso contrário:

In [158]:
tb_veic_messy[tb_veic_messy['year_map'].isna()]

,Unnamed: 0,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,guzzler,trans_dscr,tCharger,sCharger,atvType,fuelType2,rangeA,evMotor,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb,year_num_errado,mfrCodeDffr,year_num,year_map
0,0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.0,Rear-Wheel Drive,9011,(FFS),-1,1600,0,Regular,Regular Gasoline,-1,-1,25,0.0,0,0.0,0.0,0.0,0.0,0,0,1,0,0,Alfa Romeo,Spider Veloce 2000,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,23.3333,0.0,35.0,0.0,Two Seaters,1985,-1250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985a,1,1985,NaN

In [155]:
tb_veic_messy['displ'].isna()

0        False
1        False
2        False
3        False
4        False
         ...
37838    False
37839    False
37840    False
37841    False
37842    False
Name: displ, Length: 37843, dtype: bool

O método `.notna()` (das `Series`) faz o contrário:

In [159]:
tb_veic_messy['displ'].notna()

0        True
1        True
2        True
3        True
4        True
         ...
37838    True
37839    True
37840    True
37841    True
37842    True
Name: displ, Length: 37843, dtype: bool

In [160]:
mask_na_displ = tb_veic_messy['displ'].isna()
tb_displ_na = tb_veic_messy[mask_na_displ]
tb_displ_na.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 120 entries, 7138 to 30975
Data columns (total 88 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       120 non-null    int64
 1   barrels08        120 non-null    float64
 2   barrelsA08       120 non-null    float64
 3   charge120        120 non-null    float64
 4   charge240        120 non-null    float64
 5   city08           120 non-null    int64
 6   city08U          120 non-null    float64
 7   cityA08          120 non-null    int64
 8   cityA08U         120 non-null    float64
 9   cityCD           120 non-null    float64
 10  cityE            120 non-null    float64
 11  cityUF           120 non-null    float64
 12  co2              120 non-null    int64
 13  co2A             120 non-null    int64
 14  co2TailpipeAGpm  120 non-null    float64
 15  co2TailpipeGpm   120 non-null    float64
 16  comb08           120 non-null    int64
 17  comb08U          120 non-null    float64
 18  combA08          120 non-null    int64
 19  combA08U         120 non-null    float64
 20  combE            120 non-null    float64
 21  combinedCD       120 non-null    float64
 22  combinedUF       120 non-null    float64
 23  cylinders        0 non-null      float64
 24  displ            0 non-null      float64
 25  drive            112 non-null    object
 26  engId            120 non-null    int64
 27  eng_dscr         9 non-null      object
 28  feScore          120 non-null    int64
 29  fuelCost08       120 non-null    int64
 30  fuelCostA08      120 non-null    int64
 31  fuelType         120 non-null    object
 32  fuelType1        120 non-null    object
 33  ghgScore         120 non-null    int64
 34  ghgScoreA        120 non-null    int64
 35  highway08        120 non-null    int64
 36  highway08U       120 non-null    float64
 37  highwayA08       120 non-null    int64
 38  highwayA08U      120 non-null    float64
 39  highwayCD        120 non-null    float64
 40  highwayE         120 non-null    float64
 41  highwayUF        120 non-null    float64
 42  hlv              120 non-null    int64
 43  hpv              120 non-null    int64
 44  id               120 non-null    int64
 45  lv2              120 non-null    int64
 46  lv4              120 non-null    int64
 47  make             120 non-null    object
 48  model            120 non-null    object
 49  mpgData          120 non-null    object
 50  phevBlended      120 non-null    bool
 51  pv2              120 non-null    int64
 52  pv4              120 non-null    int64
 53  range            120 non-null    int64
 54  rangeCity        120 non-null    float64
 55  rangeCityA       120 non-null    float64
 56  rangeHwy         120 non-null    float64
 57  rangeHwyA        120 non-null    float64
 58  trany            111 non-null    object
 59  UCity            120 non-null    float64
 60  UCityA           120 non-null    float64
 61  UHighway         120 non-null    float64
 62  UHighwayA        120 non-null    float64
 63  VClass           120 non-null    object
 64  year             120 non-null    object
 65  youSaveSpend     120 non-null    int64
 66  guzzler          0 non-null      object
 67  trans_dscr       0 non-null      object
 68  tCharger         2 non-null      object
 69  sCharger         0 non-null      object
 70  atvType          118 non-null    object
 71  fuelType2        0 non-null      object
 72  rangeA           0 non-null      object
 73  evMotor          117 non-null    object
 74  mfrCode          92 non-null     object
 75  c240Dscr         37 non-null     object
 76  charge240b       120 non-null    float64
 77  c240bDscr        36 non-null     object
 78  createdOn        120 non-null    object
 79  modifiedOn       120 non-null    object
 80  startStop        118 non-null    object
 81  phevCity         120 non-null    int64
 82  phevHwy          120 non-null    int64
 83  phevComb         120 non-null    int64
 84  year_num_errado  120 non-null    object
 85  mfrCodeDffr      120 non-null    int64
 86  year_num         120 non-null    int64
 87  year_map         120 non-null    float64
dtypes: bool(1), float64(33), int64(29), object(25)
memory usage: 82.6+ KB

In [161]:
tb_veic_messy

,Unnamed: 0,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,guzzler,trans_dscr,tCharger,sCharger,atvType,fuelType2,rangeA,evMotor,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb,year_num_errado,mfrCodeDffr,year_num,year_map
0,0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.0,Rear-Wheel Drive,9011,(FFS),-1,1600,0,Regular,Regular Gasoline,-1,-1,25,0.0,0,0.0,0.0,0.0,0.0,0,0,1,0,0,Alfa Romeo,Spider Veloce 2000,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,23.3333,0.0,35.0000,0.0,Two Seaters,1985,-1250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985a,1,1985,NaN
1,1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,12.0,4.9,Rear-Wheel Drive,22020,(GUZZLER),-1,3050,0,Regular,Regular Gasoline,-1,-1,14,0.0,0,0.0,0.0,0.0,0.0,0,0,10,0,0,Ferrari,Testarossa,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,11.0000,0.0,19.0000,0.0,Two Seaters,1985,-8500,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985,1,1985,1985.0
2,2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,329.148148,27,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,2100,(FFS),-1,1250,0,Regular,Regular Gasoline,-1,-1,33,0.0,0,0.0,0.0,0.0,0.0,19,77,100,0,0,Dodge,Charger,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,29.0000,0.0,47.0000,0.0,Subcompact Cars,1985,500,NaN,SIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985,1,1985,1985.0
3,3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,8.0,5.2,Rear-Wheel Drive,2850,NaN,-1,3050,0,Regular,Regular Gasoline,-1,-1,12,0.0,0,0.0,0.0,0.0,0.0,0,0,1000,0,0,Dodge,B150/B250 Wagon 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Automatic 3-spd,12.2222,0.0,16.6667,0.0,Vans,1985,-8500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985,1,1985,1985.0
4,4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,2150,0,Premium,Premium Gasoline,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,10000,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,21.0000,0.0,32.0000,0.0,Compact Cars,1993,-4000,NaN,NaN,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1993,1,1993,1993.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37838,37838,14.982273,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,403.954545,22,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,66030,(FFS),-1,1500,0,Regular,Regular Gasoline,-1,-1,26,0.0,0,0.0,0.0,0.0,0.0,0,0,9995,0,14,Subaru,Legacy,N,False,0,90,0,0.0,0.0,0.0,0.0,Automatic 4-spd,24.0000,0.0,37.0000,0.0,Compact Cars,1993,-750,NaN,CLKUP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1993,1,1993,1993.0
37839,37839,14.330870,0.0,0.0,0.0,20,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,386.391304,23,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,66030,(FFS),-1,1450,0,Regular,Regular Gasoline,-1,-1,28,0.0,0,0.0,0.0,0.0,0.0,0,0,9996,0,14,Subaru,Legacy,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,25.0000,0.0,39.0000,0.0,Compact Cars,1993,-500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1993,1,1993,1993.0
37840,37840,15.695714,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66030,(FFS),-1,1600,0,Regular,Regular Gasoline,-1,-1,24,0.0,0,0.0,0.0,0.0,0.0,0,0,9997,0,14,Subaru,Legacy AWD,Y,False,0,90,0,0.0,0.0,0.0,0.0,Automatic 4-spd,23.0000,0.0,34.0000,0.0,Compact Cars,1993,-1250,NaN,CLKUP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1993,1,1993,1993.0
37841,37841,15.695714,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66030,(FFS),-1,1600,0,Regular,Regular Gasoline,-1,-1,24,0.0,0,0.0,0.0,0.0,0.0,0,0,9998,0,14,Subaru,Legacy AWD,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,23.0000,0.0,34.0000,0.0,Compact Cars,1993,-1250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1993,1,1993,1993.0
37842,37842,18.311667,0.0,0.0,0.0,16,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,493.722222,18,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,2250,0,Premium,Premium Gasoline,-1,-1,21,0.0,0,0.0,0.0,0.0,0.0,0,0,9999,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,Automatic 4-spd,20.0000,0.0,29.0000,0.0,Compact Cars,1993,-4500,NaN,CLKUP,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1993,1,1993,1993.0

In [162]:
sum(tb_veic_messy['displ'].isna())

120

### O método `.isna()` em DataFrames

Além de sua utilização em `Series`, o método `.isna()` pode ser utilizado em DataFrames: o resultado será um DataFrame de máscaras com a avaliação do método aplicada à cada coluna:

In [163]:
tb_veic_messy.isna()

,Unnamed: 0,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,guzzler,trans_dscr,tCharger,sCharger,atvType,fuelType2,rangeA,evMotor,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb,year_num_errado,mfrCodeDffr,year_num,year_map
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37838,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False,False,False,False,False
37839,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False,False,False,False,False
37840,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False,False,False,False,False
37841,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False,False,False,False,False
37842,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False,False,False,False,False

Agora podemos utilizar o método `.sum(axis = 1)` para contabilizar o número de NAs em cada linha!

In [164]:
tb_veic_messy.isna().sum(axis = 1)

0        13
1        11
2        11
3        13
4        11
         ..
37838    11
37839    12
37840    11
37841    12
37842    10
Length: 37843, dtype: int64

In [165]:
tb_veic_messy['num_val_na'] = tb_veic_messy.isna().sum(axis = 1)

In [166]:
tb_veic_messy.head()

,Unnamed: 0,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,guzzler,trans_dscr,tCharger,sCharger,atvType,fuelType2,rangeA,evMotor,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb,year_num_errado,mfrCodeDffr,year_num,year_map,num_val_na
0,0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.0,Rear-Wheel Drive,9011,(FFS),-1,1600,0,Regular,Regular Gasoline,-1,-1,25,0.0,0,0.0,0.0,0.0,0.0,0,0,1,0,0,Alfa Romeo,Spider Veloce 2000,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,23.3333,0.0,35.0000,0.0,Two Seaters,1985,-1250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985a,1,1985,NaN,13
1,1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,12.0,4.9,Rear-Wheel Drive,22020,(GUZZLER),-1,3050,0,Regular,Regular Gasoline,-1,-1,14,0.0,0,0.0,0.0,0.0,0.0,0,0,10,0,0,Ferrari,Testarossa,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,11.0000,0.0,19.0000,0.0,Two Seaters,1985,-8500,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985,1,1985,1985.0,11
2,2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,329.148148,27,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,2100,(FFS),-1,1250,0,Regular,Regular Gasoline,-1,-1,33,0.0,0,0.0,0.0,0.0,0.0,19,77,100,0,0,Dodge,Charger,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,29.0000,0.0,47.0000,0.0,Subcompact Cars,1985,500,NaN,SIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985,1,1985,1985.0,11
3,3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,8.0,5.2,Rear-Wheel Drive,2850,NaN,-1,3050,0,Regular,Regular Gasoline,-1,-1,12,0.0,0,0.0,0.0,0.0,0.0,0,0,1000,0,0,Dodge,B150/B250 Wagon 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Automatic 3-spd,12.2222,0.0,16.6667,0.0,Vans,1985,-8500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985,1,1985,1985.0,13
4,4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,2150,0,Premium,Premium Gasoline,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,10000,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,21.0000,0.0,32.0000,0.0,Compact Cars,1993,-4000,NaN,NaN,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1993,1,1993,1993.0,11

In [167]:
tb_veic_messy['num_val_na'].describe()

count    37843.000000
mean        11.312581
std          1.288592
min          4.000000
25%         11.000000
50%         12.000000
75%         12.000000
max         14.000000
Name: num_val_na, dtype: float64

Com essa nova coluna podemos construir filtros sobre a **completude** das linhas, ou seja, quantas colunas dela tem valores missing:

In [168]:
mask_num_na = tb_veic_messy['num_val_na'] < 10
mask_num_na

0        False
1        False
2        False
3        False
4        False
         ...
37838    False
37839    False
37840    False
37841    False
37842    False
Name: num_val_na, Length: 37843, dtype: bool

In [169]:
tb_veic_messy[mask_num_na].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4041 entries, 100 to 37827
Data columns (total 89 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       4041 non-null   int64
 1   barrels08        4041 non-null   float64
 2   barrelsA08       4041 non-null   float64
 3   charge120        4041 non-null   float64
 4   charge240        4041 non-null   float64
 5   city08           4041 non-null   int64
 6   city08U          4041 non-null   float64
 7   cityA08          4041 non-null   int64
 8   cityA08U         4041 non-null   float64
 9   cityCD           4041 non-null   float64
 10  cityE            4041 non-null   float64
 11  cityUF           4041 non-null   float64
 12  co2              4041 non-null   int64
 13  co2A             4041 non-null   int64
 14  co2TailpipeAGpm  4041 non-null   float64
 15  co2TailpipeGpm   4041 non-null   float64
 16  comb08           4041 non-null   int64
 17  comb08U          4041 non-null   float64
 18  combA08          4041 non-null   int64
 19  combA08U         4041 non-null   float64
 20  combE            4041 non-null   float64
 21  combinedCD       4041 non-null   float64
 22  combinedUF       4041 non-null   float64
 23  cylinders        4005 non-null   float64
 24  displ            4005 non-null   float64
 25  drive            4041 non-null   object
 26  engId            4041 non-null   int64
 27  eng_dscr         3515 non-null   object
 28  feScore          4041 non-null   int64
 29  fuelCost08       4041 non-null   int64
 30  fuelCostA08      4041 non-null   int64
 31  fuelType         4041 non-null   object
 32  fuelType1        4041 non-null   object
 33  ghgScore         4041 non-null   int64
 34  ghgScoreA        4041 non-null   int64
 35  highway08        4041 non-null   int64
 36  highway08U       4041 non-null   float64
 37  highwayA08       4041 non-null   int64
 38  highwayA08U      4041 non-null   float64
 39  highwayCD        4041 non-null   float64
 40  highwayE         4041 non-null   float64
 41  highwayUF        4041 non-null   float64
 42  hlv              4041 non-null   int64
 43  hpv              4041 non-null   int64
 44  id               4041 non-null   int64
 45  lv2              4041 non-null   int64
 46  lv4              4041 non-null   int64
 47  make             4041 non-null   object
 48  model            4041 non-null   object
 49  mpgData          4041 non-null   object
 50  phevBlended      4041 non-null   bool
 51  pv2              4041 non-null   int64
 52  pv4              4041 non-null   int64
 53  range            4041 non-null   int64
 54  rangeCity        4041 non-null   float64
 55  rangeCityA       4041 non-null   float64
 56  rangeHwy         4041 non-null   float64
 57  rangeHwyA        4041 non-null   float64
 58  trany            4041 non-null   object
 59  UCity            4041 non-null   float64
 60  UCityA           4041 non-null   float64
 61  UHighway         4041 non-null   float64
 62  UHighwayA        4041 non-null   float64
 63  VClass           4041 non-null   object
 64  year             4041 non-null   object
 65  youSaveSpend     4041 non-null   int64
 66  guzzler          408 non-null    object
 67  trans_dscr       601 non-null    object
 68  tCharger         2041 non-null   object
 69  sCharger         279 non-null    object
 70  atvType          1928 non-null   object
 71  fuelType2        1371 non-null   object
 72  rangeA           1366 non-null   object
 73  evMotor          417 non-null    object
 74  mfrCode          3180 non-null   object
 75  c240Dscr         36 non-null     object
 76  charge240b       4041 non-null   float64
 77  c240bDscr        36 non-null     object
 78  createdOn        4041 non-null   object
 79  modifiedOn       4041 non-null   object
 80  startStop        3101 non-null   object
 81  phevCity         4041 non-null   int64
 82  phevHwy          4041 non-null   int64
 83  phevComb         4041 non-null   int64
 84  year_num_errado  4041 non-null   object
 85  mfrCodeDffr      4041 non-null   int64
 86  year_num         4041 non-null   int64
 87  year_map         4041 non-null   float64
 88  num_val_na       4041 non-null   int64
dtypes: bool(1), float64(33), int64(30), object(25)
memory usage: 2.7+ MB

### Calculando a % de Valores NA

Utilizando o que construímos até agora, podemos construir uma coluna com a informação da % de linhas que apresentam valores NAs.

In [171]:
tb_veic_messy.shape

(37843, 89)

In [172]:
tb_veic_messy.isna().sum(axis = 1)

0        13
1        11
2        11
3        13
4        11
         ..
37838    11
37839    12
37840    11
37841    12
37842    10
Length: 37843, dtype: int64

In [173]:
(tb_veic_messy.isna().sum(axis = 1)/tb_veic_messy.shape[1]).describe()

count    37843.000000
mean         0.127108
std          0.014479
min          0.044944
25%          0.123596
50%          0.134831
75%          0.134831
max          0.157303
dtype: float64

## Removendo (***dropando***) colunas 
Como vimos antes, o método `.drop()` pode ser utilizado para remover linhas ou colunas. Quando queremos remover uma coluna de nosso tabela devemos usar um dois dois argumentos abaixo:

1. `axis=1` ou
1. `columns = ['nome_da_coluna1', 'nome_da_coluna2' ,...]`

In [176]:
tb_veic_messy.head()

,Unnamed: 0,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,guzzler,trans_dscr,tCharger,sCharger,atvType,fuelType2,rangeA,evMotor,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb,year_num_errado,mfrCodeDffr,year_num,year_map,num_val_na
0,0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.0,Rear-Wheel Drive,9011,(FFS),-1,1600,0,Regular,Regular Gasoline,-1,-1,25,0.0,0,0.0,0.0,0.0,0.0,0,0,1,0,0,Alfa Romeo,Spider Veloce 2000,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,23.3333,0.0,35.0000,0.0,Two Seaters,1985,-1250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985a,1,1985,NaN,13
1,1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,12.0,4.9,Rear-Wheel Drive,22020,(GUZZLER),-1,3050,0,Regular,Regular Gasoline,-1,-1,14,0.0,0,0.0,0.0,0.0,0.0,0,0,10,0,0,Ferrari,Testarossa,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,11.0000,0.0,19.0000,0.0,Two Seaters,1985,-8500,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985,1,1985,1985.0,11
2,2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,329.148148,27,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,2100,(FFS),-1,1250,0,Regular,Regular Gasoline,-1,-1,33,0.0,0,0.0,0.0,0.0,0.0,19,77,100,0,0,Dodge,Charger,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,29.0000,0.0,47.0000,0.0,Subcompact Cars,1985,500,NaN,SIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985,1,1985,1985.0,11
3,3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,8.0,5.2,Rear-Wheel Drive,2850,NaN,-1,3050,0,Regular,Regular Gasoline,-1,-1,12,0.0,0,0.0,0.0,0.0,0.0,0,0,1000,0,0,Dodge,B150/B250 Wagon 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Automatic 3-spd,12.2222,0.0,16.6667,0.0,Vans,1985,-8500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985,1,1985,1985.0,13
4,4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,2150,0,Premium,Premium Gasoline,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,10000,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,21.0000,0.0,32.0000,0.0,Compact Cars,1993,-4000,NaN,NaN,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1993,1,1993,1993.0,11

In [177]:
tb_veic_messy.drop('barrels08', axis = 1)

,Unnamed: 0,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,guzzler,trans_dscr,tCharger,sCharger,atvType,fuelType2,rangeA,evMotor,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb,year_num_errado,mfrCodeDffr,year_num,year_map,num_val_na
0,0,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.0,Rear-Wheel Drive,9011,(FFS),-1,1600,0,Regular,Regular Gasoline,-1,-1,25,0.0,0,0.0,0.0,0.0,0.0,0,0,1,0,0,Alfa Romeo,Spider Veloce 2000,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,23.3333,0.0,35.0000,0.0,Two Seaters,1985,-1250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985a,1,1985,NaN,13
1,1,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,12.0,4.9,Rear-Wheel Drive,22020,(GUZZLER),-1,3050,0,Regular,Regular Gasoline,-1,-1,14,0.0,0,0.0,0.0,0.0,0.0,0,0,10,0,0,Ferrari,Testarossa,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,11.0000,0.0,19.0000,0.0,Two Seaters,1985,-8500,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985,1,1985,1985.0,11
2,2,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,329.148148,27,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,2100,(FFS),-1,1250,0,Regular,Regular Gasoline,-1,-1,33,0.0,0,0.0,0.0,0.0,0.0,19,77,100,0,0,Dodge,Charger,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,29.0000,0.0,47.0000,0.0,Subcompact Cars,1985,500,NaN,SIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985,1,1985,1985.0,11
3,3,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,8.0,5.2,Rear-Wheel Drive,2850,NaN,-1,3050,0,Regular,Regular Gasoline,-1,-1,12,0.0,0,0.0,0.0,0.0,0.0,0,0,1000,0,0,Dodge,B150/B250 Wagon 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Automatic 3-spd,12.2222,0.0,16.6667,0.0,Vans,1985,-8500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985,1,1985,1985.0,13
4,4,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,2150,0,Premium,Premium Gasoline,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,10000,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,21.0000,0.0,32.0000,0.0,Compact Cars,1993,-4000,NaN,NaN,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1993,1,1993,1993.0,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37838,37838,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,403.954545,22,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,66030,(FFS),-1,1500,0,Regular,Regular Gasoline,-1,-1,26,0.0,0,0.0,0.0,0.0,0.0,0,0,9995,0,14,Subaru,Legacy,N,False,0,90,0,0.0,0.0,0.0,0.0,Automatic 4-spd,24.0000,0.0,37.0000,0.0,Compact Cars,1993,-750,NaN,CLKUP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1993,1,1993,1993.0,11
37839,37839,0.0,0.0,0.0,20,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,386.391304,23,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,66030,(FFS),-1,1450,0,Regular,Regular Gasoline,-1,-1,28,0.0,0,0.0,0.0,0.0,0.0,0,0,9996,0,14,Subaru,Legacy,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,25.0000,0.0,39.0000,0.0,Compact Cars,1993,-500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1993,1,1993,1993.0,12
37840,37840,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66030,(FFS),-1,1600,0,Regular,Regular Gasoline,-1,-1,24,0.0,0,0.0,0.0,0.0,0.0,0,0,9997,0,14,Subaru,Legacy AWD,Y,False,0,90,0,0.0,0.0,0.0,0.0,Automatic 4-spd,23.0000,0.0,34.0000,0.0,Compact Cars,1993,-1250,NaN,CLKUP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1993,1,1993,1993.0,11
37841,37841,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66030,(FFS),-1,1600,0,Regular,Regular Gasoline,-1,-1,24,0.0,0,0.0,0.0,0.0,0.0,0,0,9998,0,14,Subaru,Legacy AWD,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,23.0000,0.0,34.0000,0.0,Compact Cars,1993,-1250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1993,1,1993,1993.0,12
37842,37842,0.0,0.0,0.0,16,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,493.722222,18,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,2250,0,Premium,Premium Gasoline,-1,-1,21,0.0,0,0.0,0.0,0.0,0.0,0,0,9999,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,Automatic 4-spd,20.0000,0.0,29.0000,0.0,Compact Cars,1993,-4500,NaN,CLKUP,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1993,1,1993,1993.0,10

In [179]:
tb_sem_barrels = tb_veic_messy.drop(columns = ['barrels08', 'barrelsA08']).head()

In [180]:
tb_sem_barrels

,Unnamed: 0,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,guzzler,trans_dscr,tCharger,sCharger,atvType,fuelType2,rangeA,evMotor,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb,year_num_errado,mfrCodeDffr,year_num,year_map,num_val_na
0,0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.0,Rear-Wheel Drive,9011,(FFS),-1,1600,0,Regular,Regular Gasoline,-1,-1,25,0.0,0,0.0,0.0,0.0,0.0,0,0,1,0,0,Alfa Romeo,Spider Veloce 2000,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,23.3333,0.0,35.0000,0.0,Two Seaters,1985,-1250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985a,1,1985,NaN,13
1,1,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,12.0,4.9,Rear-Wheel Drive,22020,(GUZZLER),-1,3050,0,Regular,Regular Gasoline,-1,-1,14,0.0,0,0.0,0.0,0.0,0.0,0,0,10,0,0,Ferrari,Testarossa,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,11.0000,0.0,19.0000,0.0,Two Seaters,1985,-8500,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985,1,1985,1985.0,11
2,2,0.0,0.0,23,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,329.148148,27,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,2100,(FFS),-1,1250,0,Regular,Regular Gasoline,-1,-1,33,0.0,0,0.0,0.0,0.0,0.0,19,77,100,0,0,Dodge,Charger,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,29.0000,0.0,47.0000,0.0,Subcompact Cars,1985,500,NaN,SIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985,1,1985,1985.0,11
3,3,0.0,0.0,10,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,8.0,5.2,Rear-Wheel Drive,2850,NaN,-1,3050,0,Regular,Regular Gasoline,-1,-1,12,0.0,0,0.0,0.0,0.0,0.0,0,0,1000,0,0,Dodge,B150/B250 Wagon 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Automatic 3-spd,12.2222,0.0,16.6667,0.0,Vans,1985,-8500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1985,1,1985,1985.0,13
4,4,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,2150,0,Premium,Premium Gasoline,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,10000,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,21.0000,0.0,32.0000,0.0,Compact Cars,1993,-4000,NaN,NaN,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0,1993,1,1993,1993.0,11

### Removendo colunas condicionalmente

Uma técnica importante é a remoção de colunas através de condições. Por exemplo, nosso DataFrame pode ter colunas com um único valor. Vamos utilizar o método `.drop()` para remover essas colunas:

In [181]:
tb_veic_messy.columns

Index(['Unnamed: 0', 'barrels08', 'barrelsA08', 'charge120', 'charge240',
       'city08', 'city08U', 'cityA08', 'cityA08U', 'cityCD', 'cityE', 'cityUF',
       'co2', 'co2A', 'co2TailpipeAGpm', 'co2TailpipeGpm', 'comb08', 'comb08U',
       'combA08', 'combA08U', 'combE', 'combinedCD', 'combinedUF', 'cylinders',
       'displ', 'drive', 'engId', 'eng_dscr', 'feScore', 'fuelCost08',
       'fuelCostA08', 'fuelType', 'fuelType1', 'ghgScore', 'ghgScoreA',
       'highway08', 'highway08U', 'highwayA08', 'highwayA08U', 'highwayCD',
       'highwayE', 'highwayUF', 'hlv', 'hpv', 'id', 'lv2', 'lv4', 'make',
       'model', 'mpgData', 'phevBlended', 'pv2', 'pv4', 'range', 'rangeCity',
       'rangeCityA', 'rangeHwy', 'rangeHwyA', 'trany', 'UCity', 'UCityA',
       'UHighway', 'UHighwayA', 'VClass', 'year', 'youSaveSpend', 'guzzler',
       'trans_dscr', 'tCharger', 'sCharger', 'atvType', 'fuelType2', 'rangeA',
       'evMotor', 'mfrCode', 'c240Dscr', 'charge240b', 'c240bDscr',
       'createdOn', 'modifiedOn', 'startStop', 'phevCity', 'phevHwy',
       'phevComb', 'year_num_errado', 'mfrCodeDffr', 'year_num', 'year_map',
       'num_val_na'],
      dtype='object')

In [185]:
len(tb_veic_messy['eng_dscr'].unique())

542

In [186]:
colunas_unique = []
for coluna in tb_veic_messy.columns:
    n_valores = len(tb_veic_messy[coluna].unique())
    if n_valores == 1:
        colunas_unique.append(coluna)
print(colunas_unique)

['charge120', 'mfrCodeDffr']

In [189]:
tb_veic_messy['mfrCodeDffr'].unique()

array([1])

Vamos praticar nosso raciocinio funcional transformando o loop acima em um list comprehension!

In [191]:
colunas_unique = [coluna for coluna in tb_veic_messy.columns if len(tb_veic_messy[coluna].unique()) == 1]
colunas_unique

['charge120', 'mfrCodeDffr']

Agora, com nossa lista de colunas, podemos utilizar o método `.drop()` para tratar nosso DataFrame:

In [192]:
tb_veic_messy.drop(columns = colunas_unique).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37843 entries, 0 to 37842
Data columns (total 87 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       37843 non-null  int64
 1   barrels08        37843 non-null  float64
 2   barrelsA08       37843 non-null  float64
 3   charge240        37843 non-null  float64
 4   city08           37843 non-null  int64
 5   city08U          37843 non-null  float64
 6   cityA08          37843 non-null  int64
 7   cityA08U         37843 non-null  float64
 8   cityCD           37843 non-null  float64
 9   cityE            37843 non-null  float64
 10  cityUF           37843 non-null  float64
 11  co2              37843 non-null  int64
 12  co2A             37843 non-null  int64
 13  co2TailpipeAGpm  37843 non-null  float64
 14  co2TailpipeGpm   37843 non-null  float64
 15  comb08           37843 non-null  int64
 16  comb08U          37843 non-null  float64
 17  combA08          37843 non-null  int64
 18  combA08U         37843 non-null  float64
 19  combE            37843 non-null  float64
 20  combinedCD       37843 non-null  float64
 21  combinedUF       37843 non-null  float64
 22  cylinders        37720 non-null  float64
 23  displ            37723 non-null  float64
 24  drive            36654 non-null  object
 25  engId            37843 non-null  int64
 26  eng_dscr         22440 non-null  object
 27  feScore          37843 non-null  int64
 28  fuelCost08       37843 non-null  int64
 29  fuelCostA08      37843 non-null  int64
 30  fuelType         37843 non-null  object
 31  fuelType1        37843 non-null  object
 32  ghgScore         37843 non-null  int64
 33  ghgScoreA        37843 non-null  int64
 34  highway08        37843 non-null  int64
 35  highway08U       37843 non-null  float64
 36  highwayA08       37843 non-null  int64
 37  highwayA08U      37843 non-null  float64
 38  highwayCD        37843 non-null  float64
 39  highwayE         37843 non-null  float64
 40  highwayUF        37843 non-null  float64
 41  hlv              37843 non-null  int64
 42  hpv              37843 non-null  int64
 43  id               37843 non-null  int64
 44  lv2              37843 non-null  int64
 45  lv4              37843 non-null  int64
 46  make             37843 non-null  object
 47  model            37843 non-null  object
 48  mpgData          37843 non-null  object
 49  phevBlended      37843 non-null  bool
 50  pv2              37843 non-null  int64
 51  pv4              37843 non-null  int64
 52  range            37843 non-null  int64
 53  rangeCity        37843 non-null  float64
 54  rangeCityA       37843 non-null  float64
 55  rangeHwy         37843 non-null  float64
 56  rangeHwyA        37843 non-null  float64
 57  trany            37832 non-null  object
 58  UCity            37843 non-null  float64
 59  UCityA           37843 non-null  float64
 60  UHighway         37843 non-null  float64
 61  UHighwayA        37843 non-null  float64
 62  VClass           37843 non-null  object
 63  year             37843 non-null  object
 64  youSaveSpend     37843 non-null  int64
 65  guzzler          2281 non-null   object
 66  trans_dscr       15047 non-null  object
 67  tCharger         5186 non-null   object
 68  sCharger         666 non-null    object
 69  atvType          3072 non-null   object
 70  fuelType2        1408 non-null   object
 71  rangeA           1403 non-null   object
 72  evMotor          562 non-null    object
 73  mfrCode          7025 non-null   object
 74  c240Dscr         37 non-null     object
 75  charge240b       37843 non-null  float64
 76  c240bDscr        36 non-null     object
 77  createdOn        37843 non-null  object
 78  modifiedOn       37843 non-null  object
 79  startStop        6138 non-null   object
 80  phevCity         37843 non-null  int64
 81  phevHwy          37843 non-null  int64
 82  phevComb         37843 non-null  int64
 83  year_num_errado  37843 non-null  object
 84  year_num         37843 non-null  int64
 85  year_map         37842 non-null  float64
 86  num_val_na       37843 non-null  int64
dtypes: bool(1), float64(32), int64(29), object(25)
memory usage: 24.9+ MB

### Colunas com baixa variância

O exemplo acima pode ser generalizado para eliminar mais colunas: podemos eliminar colunas numéricas que apresentem pouca variação. Para tanto, vamos utilizar o conceito de quantis (vamos aprender mais a fundo que são quantis no módulo II). Vamos começar investigando como fazer isto usando a coluna `cityA08`:

In [193]:
tb_veic_messy['cityA08'].describe()

count    37843.000000
mean         0.520149
std          3.837874
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max        127.000000
Name: cityA08, dtype: float64

Agora vamos utilizar a função `np.quantile` para descobrir o valor abaixo do qual 90% das nossas observações estão:

In [194]:
np.quantile(tb_veic_messy['cityA08'], 0.9)

0.0

Podemos verificar que este valor é igual ao mínimo da coluna - concluímos então que pelo menos 90% das observações tem o mesmo valor (o mínimo da coluna!)

In [195]:
np.quantile(tb_veic_messy['cityA08'], 0.9) == min(tb_veic_messy['cityA08'])

True

Como podemos limpar nossas colunas utilizando o método descrito acima?

In [196]:
# DESAFIO
lista_colunas = []
for coluna in tb_veic_messy.select_dtypes(include = 'number').columns:
    if np.quantile(tb_veic_messy[coluna], 0.9) == min(tb_veic_messy[coluna]):
        lista_colunas.append(coluna)
        
lista_colunas

['barrelsA08',
 'charge120',
 'charge240',
 'cityA08',
 'cityA08U',
 'cityCD',
 'cityE',
 'cityUF',
 'co2A',
 'co2TailpipeAGpm',
 'combA08',
 'combA08U',
 'combE',
 'combinedCD',
 'combinedUF',
 'fuelCostA08',
 'ghgScoreA',
 'highwayA08',
 'highwayA08U',
 'highwayCD',
 'highwayE',
 'highwayUF',
 'range',
 'rangeCity',
 'rangeCityA',
 'rangeHwy',
 'rangeHwyA',
 'UCityA',
 'UHighwayA',
 'charge240b',
 'phevCity',
 'phevHwy',
 'phevComb',
 'mfrCodeDffr']

In [198]:
tb_veic_messy['ghgScoreA'].describe()

count    37843.000000
mean        -0.929630
std          0.627565
min         -1.000000
25%         -1.000000
50%         -1.000000
75%         -1.000000
max          8.000000
Name: ghgScoreA, dtype: float64

O método acima pode ser utilizado para limpar colunas cujos valores estejam concentrados no mínimo. Como podemos generaliza-lo para valores repetidos em qualquer posições de nosso dataset?

In [ ]:
# DESAFIO

## O método `.dropna()`

A maneira mais **direta**, *mas nem sempre correta*, de tratar NAs é removendo-os da nossa tabela. Como podemos saber quando remover NAs? Basta lembrar dos três motivos pelo qual eles aparecem:

1. Pela aplicação de funções em nosso código 
    * **Exemplo**: `.map()` que construímos acima;
1. Através de falhas na coleta/armazenagem de dados
    * **Exemplo**: em uma pesquisa física, alguns campos preenchidos estavam ilegíveis.
1. Para representar características reais da observação
    * **Exemplo**: em uma tabela de e-commerce, com o faturamento mês a mês de cada item, a coluna `desconto` pode aparecer como NA para representar produtos que não estavam promocionados

Na sua opinião, qual tipo de NA devemos manter e qual devemos excluir da base?

Uma vez determinado que vamos remover NAs temos duas formas de fazê-lo: excluindo colunas e excluindo linhas. Em geral excluímos colunas quando a quantidade de NAs é tão grande que seria impossível utilizar a informação da coluna para qualquer coisa. No caso das linhas, removemos linhas com NA **APENAS QUANDO AS COLUNAS DE NOSSA ANÁLISE FOREM IMPACTADAS!!**

Vamos ver como o método `.dropna()` pode nos ajudar aqui.

Primeiro em tudo:

In [199]:
tb_veic_messy.dropna()

Empty DataFrame
Columns: [Unnamed: 0, barrels08, barrelsA08, charge120, charge240, city08, city08U, cityA08, cityA08U, cityCD, cityE, cityUF, co2, co2A, co2TailpipeAGpm, co2TailpipeGpm, comb08, comb08U, combA08, combA08U, combE, combinedCD, combinedUF, cylinders, displ, drive, engId, eng_dscr, feScore, fuelCost08, fuelCostA08, fuelType, fuelType1, ghgScore, ghgScoreA, highway08, highway08U, highwayA08, highwayA08U, highwayCD, highwayE, highwayUF, hlv, hpv, id, lv2, lv4, make, model, mpgData, phevBlended, pv2, pv4, range, rangeCity, rangeCityA, rangeHwy, rangeHwyA, trany, UCity, UCityA, UHighway, UHighwayA, VClass, year, youSaveSpend, guzzler, trans_dscr, tCharger, sCharger, atvType, fuelType2, rangeA, evMotor, mfrCode, c240Dscr, charge240b, c240bDscr, createdOn, modifiedOn, startStop, phevCity, phevHwy, phevComb, year_num_errado, mfrCodeDffr, year_num, year_map, num_val_na]
Index: []

Agora nas linhas:

In [200]:
tb_veic_messy.dropna(axis = 0)

Empty DataFrame
Columns: [Unnamed: 0, barrels08, barrelsA08, charge120, charge240, city08, city08U, cityA08, cityA08U, cityCD, cityE, cityUF, co2, co2A, co2TailpipeAGpm, co2TailpipeGpm, comb08, comb08U, combA08, combA08U, combE, combinedCD, combinedUF, cylinders, displ, drive, engId, eng_dscr, feScore, fuelCost08, fuelCostA08, fuelType, fuelType1, ghgScore, ghgScoreA, highway08, highway08U, highwayA08, highwayA08U, highwayCD, highwayE, highwayUF, hlv, hpv, id, lv2, lv4, make, model, mpgData, phevBlended, pv2, pv4, range, rangeCity, rangeCityA, rangeHwy, rangeHwyA, trany, UCity, UCityA, UHighway, UHighwayA, VClass, year, youSaveSpend, guzzler, trans_dscr, tCharger, sCharger, atvType, fuelType2, rangeA, evMotor, mfrCode, c240Dscr, charge240b, c240bDscr, createdOn, modifiedOn, startStop, phevCity, phevHwy, phevComb, year_num_errado, mfrCodeDffr, year_num, year_map, num_val_na]
Index: []

Agora nas colunas:

In [201]:
tb_veic_messy.dropna(axis = 1)

,Unnamed: 0,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,engId,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn,phevCity,phevHwy,phevComb,year_num_errado,mfrCodeDffr,year_num,num_val_na
0,0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,9011,-1,1600,0,Regular,Regular Gasoline,-1,-1,25,0.0,0,0.0,0.0,0.0,0.0,0,0,1,0,0,Alfa Romeo,Spider Veloce 2000,Y,False,0,0,0,0.0,0.0,0.0,0.0,23.3333,0.0,35.0000,0.0,Two Seaters,1985,-1250,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1985a,1,1985,13
1,1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,22020,-1,3050,0,Regular,Regular Gasoline,-1,-1,14,0.0,0,0.0,0.0,0.0,0.0,0,0,10,0,0,Ferrari,Testarossa,N,False,0,0,0,0.0,0.0,0.0,0.0,11.0000,0.0,19.0000,0.0,Two Seaters,1985,-8500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1985,1,1985,11
2,2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,329.148148,27,0.0,0,0.0,0.0,0.0,0.0,2100,-1,1250,0,Regular,Regular Gasoline,-1,-1,33,0.0,0,0.0,0.0,0.0,0.0,19,77,100,0,0,Dodge,Charger,Y,False,0,0,0,0.0,0.0,0.0,0.0,29.0000,0.0,47.0000,0.0,Subcompact Cars,1985,500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1985,1,1985,11
3,3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,2850,-1,3050,0,Regular,Regular Gasoline,-1,-1,12,0.0,0,0.0,0.0,0.0,0.0,0,0,1000,0,0,Dodge,B150/B250 Wagon 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,12.2222,0.0,16.6667,0.0,Vans,1985,-8500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1985,1,1985,13
4,4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,66031,-1,2150,0,Premium,Premium Gasoline,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,10000,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,21.0000,0.0,32.0000,0.0,Compact Cars,1993,-4000,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1993,1,1993,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37838,37838,14.982273,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,403.954545,22,0.0,0,0.0,0.0,0.0,0.0,66030,-1,1500,0,Regular,Regular Gasoline,-1,-1,26,0.0,0,0.0,0.0,0.0,0.0,0,0,9995,0,14,Subaru,Legacy,N,False,0,90,0,0.0,0.0,0.0,0.0,24.0000,0.0,37.0000,0.0,Compact Cars,1993,-750,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1993,1,1993,11
37839,37839,14.330870,0.0,0.0,0.0,20,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,386.391304,23,0.0,0,0.0,0.0,0.0,0.0,66030,-1,1450,0,Regular,Regular Gasoline,-1,-1,28,0.0,0,0.0,0.0,0.0,0.0,0,0,9996,0,14,Subaru,Legacy,N,False,0,90,0,0.0,0.0,0.0,0.0,25.0000,0.0,39.0000,0.0,Compact Cars,1993,-500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1993,1,1993,12
37840,37840,15.695714,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,66030,-1,1600,0,Regular,Regular Gasoline,-1,-1,24,0.0,0,0.0,0.0,0.0,0.0,0,0,9997,0,14,Subaru,Legacy AWD,Y,False,0,90,0,0.0,0.0,0.0,0.0,23.0000,0.0,34.0000,0.0,Compact Cars,1993,-1250,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1993,1,1993,11
37841,37841,15.695714,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,66030,-1,1600,0,Regular,Regular Gasoline,-1,-1,24,0.0,0,0.0,0.0,0.0,0.0,0,0,9998,0,14,Subaru,Legacy AWD,N,False,0,90,0,0.0,0.0,0.0,0.0,23.0000,0.0,34.0000,0.0,Compact Cars,1993,-1250,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1993,1,1993,12
37842,37842,18.311667,0.0,0.0,0.0,16,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,493.722222,18,0.0,0,0.0,0.0,0.0,0.0,66031,-1,2250,0,Premium,Premium Gasoline,-1,-1,21,0.0,0,0.0,0.0,0.0,0.0,0,0,9999,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,20.0000,0.0,29.0000,0.0,Compact Cars,1993,-4500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1993,1,1993,10

Independente do eixo (`axis`) de aplicação, podemos especificar o `thresh` - um patamar de NAs abaixo do qual removemos uma linha ou coluna. Se escolhermos o eixo das linhas, e colocarmos o `thresh = 60`, manteremos apenas as linhas com pelo menos 60 colunas preenchidas. Já no caso das colunas, o `thresh` será o mínimo de linhas não-NA que uma coluna precisar para continuar no DataFrame.

In [203]:
tb_veic_messy.shape

(37843, 89)

In [205]:
tb_veic_messy.dropna(axis = 0, thresh = 70).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37843 entries, 0 to 37842
Data columns (total 89 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       37843 non-null  int64
 1   barrels08        37843 non-null  float64
 2   barrelsA08       37843 non-null  float64
 3   charge120        37843 non-null  float64
 4   charge240        37843 non-null  float64
 5   city08           37843 non-null  int64
 6   city08U          37843 non-null  float64
 7   cityA08          37843 non-null  int64
 8   cityA08U         37843 non-null  float64
 9   cityCD           37843 non-null  float64
 10  cityE            37843 non-null  float64
 11  cityUF           37843 non-null  float64
 12  co2              37843 non-null  int64
 13  co2A             37843 non-null  int64
 14  co2TailpipeAGpm  37843 non-null  float64
 15  co2TailpipeGpm   37843 non-null  float64
 16  comb08           37843 non-null  int64
 17  comb08U          37843 non-null  float64
 18  combA08          37843 non-null  int64
 19  combA08U         37843 non-null  float64
 20  combE            37843 non-null  float64
 21  combinedCD       37843 non-null  float64
 22  combinedUF       37843 non-null  float64
 23  cylinders        37720 non-null  float64
 24  displ            37723 non-null  float64
 25  drive            36654 non-null  object
 26  engId            37843 non-null  int64
 27  eng_dscr         22440 non-null  object
 28  feScore          37843 non-null  int64
 29  fuelCost08       37843 non-null  int64
 30  fuelCostA08      37843 non-null  int64
 31  fuelType         37843 non-null  object
 32  fuelType1        37843 non-null  object
 33  ghgScore         37843 non-null  int64
 34  ghgScoreA        37843 non-null  int64
 35  highway08        37843 non-null  int64
 36  highway08U       37843 non-null  float64
 37  highwayA08       37843 non-null  int64
 38  highwayA08U      37843 non-null  float64
 39  highwayCD        37843 non-null  float64
 40  highwayE         37843 non-null  float64
 41  highwayUF        37843 non-null  float64
 42  hlv              37843 non-null  int64
 43  hpv              37843 non-null  int64
 44  id               37843 non-null  int64
 45  lv2              37843 non-null  int64
 46  lv4              37843 non-null  int64
 47  make             37843 non-null  object
 48  model            37843 non-null  object
 49  mpgData          37843 non-null  object
 50  phevBlended      37843 non-null  bool
 51  pv2              37843 non-null  int64
 52  pv4              37843 non-null  int64
 53  range            37843 non-null  int64
 54  rangeCity        37843 non-null  float64
 55  rangeCityA       37843 non-null  float64
 56  rangeHwy         37843 non-null  float64
 57  rangeHwyA        37843 non-null  float64
 58  trany            37832 non-null  object
 59  UCity            37843 non-null  float64
 60  UCityA           37843 non-null  float64
 61  UHighway         37843 non-null  float64
 62  UHighwayA        37843 non-null  float64
 63  VClass           37843 non-null  object
 64  year             37843 non-null  object
 65  youSaveSpend     37843 non-null  int64
 66  guzzler          2281 non-null   object
 67  trans_dscr       15047 non-null  object
 68  tCharger         5186 non-null   object
 69  sCharger         666 non-null    object
 70  atvType          3072 non-null   object
 71  fuelType2        1408 non-null   object
 72  rangeA           1403 non-null   object
 73  evMotor          562 non-null    object
 74  mfrCode          7025 non-null   object
 75  c240Dscr         37 non-null     object
 76  charge240b       37843 non-null  float64
 77  c240bDscr        36 non-null     object
 78  createdOn        37843 non-null  object
 79  modifiedOn       37843 non-null  object
 80  startStop        6138 non-null   object
 81  phevCity         37843 non-null  int64
 82  phevHwy          37843 non-null  int64
 83  phevComb         37843 non-null  int64
 84  year_num_errado  37843 non-null  object
 85  mfrCodeDffr      37843 non-null  int64
 86  year_num         37843 non-null  int64
 87  year_map         37842 non-null  float64
 88  num_val_na       37843 non-null  int64
dtypes: bool(1), float64(33), int64(30), object(25)
memory usage: 25.4+ MB

In [208]:
tb_veic_messy.dropna(axis = 1, thresh = tb_veic_messy.shape[0] - 1)

,Unnamed: 0,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,engId,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn,phevCity,phevHwy,phevComb,year_num_errado,mfrCodeDffr,year_num,year_map,num_val_na
0,0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,9011,-1,1600,0,Regular,Regular Gasoline,-1,-1,25,0.0,0,0.0,0.0,0.0,0.0,0,0,1,0,0,Alfa Romeo,Spider Veloce 2000,Y,False,0,0,0,0.0,0.0,0.0,0.0,23.3333,0.0,35.0000,0.0,Two Seaters,1985,-1250,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1985a,1,1985,NaN,13
1,1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,22020,-1,3050,0,Regular,Regular Gasoline,-1,-1,14,0.0,0,0.0,0.0,0.0,0.0,0,0,10,0,0,Ferrari,Testarossa,N,False,0,0,0,0.0,0.0,0.0,0.0,11.0000,0.0,19.0000,0.0,Two Seaters,1985,-8500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1985,1,1985,1985.0,11
2,2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,329.148148,27,0.0,0,0.0,0.0,0.0,0.0,2100,-1,1250,0,Regular,Regular Gasoline,-1,-1,33,0.0,0,0.0,0.0,0.0,0.0,19,77,100,0,0,Dodge,Charger,Y,False,0,0,0,0.0,0.0,0.0,0.0,29.0000,0.0,47.0000,0.0,Subcompact Cars,1985,500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1985,1,1985,1985.0,11
3,3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,2850,-1,3050,0,Regular,Regular Gasoline,-1,-1,12,0.0,0,0.0,0.0,0.0,0.0,0,0,1000,0,0,Dodge,B150/B250 Wagon 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,12.2222,0.0,16.6667,0.0,Vans,1985,-8500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1985,1,1985,1985.0,13
4,4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,66031,-1,2150,0,Premium,Premium Gasoline,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,10000,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,21.0000,0.0,32.0000,0.0,Compact Cars,1993,-4000,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1993,1,1993,1993.0,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37838,37838,14.982273,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,403.954545,22,0.0,0,0.0,0.0,0.0,0.0,66030,-1,1500,0,Regular,Regular Gasoline,-1,-1,26,0.0,0,0.0,0.0,0.0,0.0,0,0,9995,0,14,Subaru,Legacy,N,False,0,90,0,0.0,0.0,0.0,0.0,24.0000,0.0,37.0000,0.0,Compact Cars,1993,-750,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1993,1,1993,1993.0,11
37839,37839,14.330870,0.0,0.0,0.0,20,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,386.391304,23,0.0,0,0.0,0.0,0.0,0.0,66030,-1,1450,0,Regular,Regular Gasoline,-1,-1,28,0.0,0,0.0,0.0,0.0,0.0,0,0,9996,0,14,Subaru,Legacy,N,False,0,90,0,0.0,0.0,0.0,0.0,25.0000,0.0,39.0000,0.0,Compact Cars,1993,-500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1993,1,1993,1993.0,12
37840,37840,15.695714,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,66030,-1,1600,0,Regular,Regular Gasoline,-1,-1,24,0.0,0,0.0,0.0,0.0,0.0,0,0,9997,0,14,Subaru,Legacy AWD,Y,False,0,90,0,0.0,0.0,0.0,0.0,23.0000,0.0,34.0000,0.0,Compact Cars,1993,-1250,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1993,1,1993,1993.0,11
37841,37841,15.695714,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,66030,-1,1600,0,Regular,Regular Gasoline,-1,-1,24,0.0,0,0.0,0.0,0.0,0.0,0,0,9998,0,14,Subaru,Legacy AWD,N,False,0,90,0,0.0,0.0,0.0,0.0,23.0000,0.0,34.0000,0.0,Compact Cars,1993,-1250,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1993,1,1993,1993.0,12
37842,37842,18.311667,0.0,0.0,0.0,16,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,493.722222,18,0.0,0,0.0,0.0,0.0,0.0,66031,-1,2250,0,Premium,Premium Gasoline,-1,-1,21,0.0,0,0.0,0.0,0.0,0.0,0,0,9999,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,20.0000,0.0,29.0000,0.0,Compact Cars,1993,-4500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1993,1,1993,1993.0,10

In [210]:
int(tb_veic_messy.shape[0] * 0.5)

18921

In [211]:
thresh_col = int(tb_veic_messy.shape[0] * 0.20)
thresh_col

7568

In [212]:
tb_veic_messy.dropna(axis = 1, thresh = thresh_col)

,Unnamed: 0,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,trans_dscr,charge240b,createdOn,modifiedOn,phevCity,phevHwy,phevComb,year_num_errado,mfrCodeDffr,year_num,year_map,num_val_na
0,0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.0,Rear-Wheel Drive,9011,(FFS),-1,1600,0,Regular,Regular Gasoline,-1,-1,25,0.0,0,0.0,0.0,0.0,0.0,0,0,1,0,0,Alfa Romeo,Spider Veloce 2000,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,23.3333,0.0,35.0000,0.0,Two Seaters,1985,-1250,NaN,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1985a,1,1985,NaN,13
1,1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,12.0,4.9,Rear-Wheel Drive,22020,(GUZZLER),-1,3050,0,Regular,Regular Gasoline,-1,-1,14,0.0,0,0.0,0.0,0.0,0.0,0,0,10,0,0,Ferrari,Testarossa,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,11.0000,0.0,19.0000,0.0,Two Seaters,1985,-8500,NaN,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1985,1,1985,1985.0,11
2,2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,329.148148,27,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,2100,(FFS),-1,1250,0,Regular,Regular Gasoline,-1,-1,33,0.0,0,0.0,0.0,0.0,0.0,19,77,100,0,0,Dodge,Charger,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,29.0000,0.0,47.0000,0.0,Subcompact Cars,1985,500,SIL,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1985,1,1985,1985.0,11
3,3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,8.0,5.2,Rear-Wheel Drive,2850,NaN,-1,3050,0,Regular,Regular Gasoline,-1,-1,12,0.0,0,0.0,0.0,0.0,0.0,0,0,1000,0,0,Dodge,B150/B250 Wagon 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Automatic 3-spd,12.2222,0.0,16.6667,0.0,Vans,1985,-8500,NaN,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1985,1,1985,1985.0,13
4,4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,2150,0,Premium,Premium Gasoline,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,10000,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,21.0000,0.0,32.0000,0.0,Compact Cars,1993,-4000,NaN,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1993,1,1993,1993.0,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37838,37838,14.982273,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,403.954545,22,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,66030,(FFS),-1,1500,0,Regular,Regular Gasoline,-1,-1,26,0.0,0,0.0,0.0,0.0,0.0,0,0,9995,0,14,Subaru,Legacy,N,False,0,90,0,0.0,0.0,0.0,0.0,Automatic 4-spd,24.0000,0.0,37.0000,0.0,Compact Cars,1993,-750,CLKUP,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1993,1,1993,1993.0,11
37839,37839,14.330870,0.0,0.0,0.0,20,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,386.391304,23,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,66030,(FFS),-1,1450,0,Regular,Regular Gasoline,-1,-1,28,0.0,0,0.0,0.0,0.0,0.0,0,0,9996,0,14,Subaru,Legacy,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,25.0000,0.0,39.0000,0.0,Compact Cars,1993,-500,NaN,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1993,1,1993,1993.0,12
37840,37840,15.695714,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66030,(FFS),-1,1600,0,Regular,Regular Gasoline,-1,-1,24,0.0,0,0.0,0.0,0.0,0.0,0,0,9997,0,14,Subaru,Legacy AWD,Y,False,0,90,0,0.0,0.0,0.0,0.0,Automatic 4-spd,23.0000,0.0,34.0000,0.0,Compact Cars,1993,-1250,CLKUP,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1993,1,1993,1993.0,11
37841,37841,15.695714,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66030,(FFS),-1,1600,0,Regular,Regular Gasoline,-1,-1,24,0.0,0,0.0,0.0,0.0,0.0,0,0,9998,0,14,Subaru,Legacy AWD,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,23.0000,0.0,34.0000,0.0,Compact Cars,1993,-1250,NaN,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1993,1,1993,1993.0,12
37842,37842,18.311667,0.0,0.0,0.0,16,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,493.722222,18,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,2250,0,Premium,Premium Gasoline,-1,-1,21,0.0,0,0.0,0.0,0.0,0.0,0,0,9999,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,Automatic 4-spd,20.0000,0.0,29.0000,0.0,Compact Cars,1993,-4500,CLKUP,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,1993,1,1993,1993.0,10

## O método `.fillna()`

Em algumas condições (quais?) é melhor substituir os ***missing values*** por algum outro valor. Para tanto vamos utilizar o método `.fillna()`.

In [213]:
tb_veic_messy['trans_dscr'].isna().sum(axis = 0)

22796

In [215]:
tb_veic_messy['trans_dscr'].unique()

array([nan, 'SIL', '2MODE CLKUP', 'CLKUP', '2MODE', '3MODE CLKUP',
       '2MODE 2LKUP', '3MODE', '4MODE', 'Creeper', 'SIL Creeper',
       'EMS 2MODE', '2LKUP', '2MODE CLKUP FW', 'DC/FW', 'EMS',
       '2MODE VLKUP', 'EMS 2MODE CLKU', '3MODE 2LKUP', 'EMS 3MODE',
       'VMODE CLKUP', 'VLKUP', 'EMS 2MODE CLKUP', 'EMS CLKUP',
       'EMS CMODE CLKUP', 'SIL CLKUP', 'CMODE CLKUP', 'VMODE', 'CMODE',
       '3LKUP', 'EMS 3MODE CLKUP', 'SIL EMS', '6MODE', '4MODE CLKUP',
       'VMODE VLKUP', '6MODE CLKUP', 'SIL 3MODE', 'LONG RATIO',
       'CMODE VLKUP', 'SIL 3MODE CLKUP', '3MODE VLKUP', 'Overdrive',
       'Lockup', '3MODE CLKUP FW', 'SIL 2MODE CLKUP', 'EMS 5MODE',
       '2MODE DC/FW', 'fuel injection', '2MODE 3LKUP', 'Lockup A3',
       'SIL CMODE', 'Elec Overdrive', 'Mech Overdrive'], dtype=object)

In [218]:
tb_veic_messy['trans_dscr']

0          NaN
1          NaN
2          SIL
3          NaN
4          NaN
         ...
37838    CLKUP
37839      NaN
37840    CLKUP
37841      NaN
37842    CLKUP
Name: trans_dscr, Length: 37843, dtype: object

In [217]:
tb_veic_messy['trans_dscr'].fillna('Não Preenchido')

0        Não Preenchido
1        Não Preenchido
2                   SIL
3        Não Preenchido
4        Não Preenchido
              ...
37838             CLKUP
37839    Não Preenchido
37840             CLKUP
37841    Não Preenchido
37842             CLKUP
Name: trans_dscr, Length: 37843, dtype: object

In [219]:
tb_veic_messy['trans_dscr_fna'] = tb_veic_messy['trans_dscr'].fillna('OUTROS')

In [220]:
tb_veic_messy['trans_dscr_fna'].value_counts()

OUTROS             22796
CLKUP               7809
SIL                 2189
2MODE CLKUP         1235
Creeper              525
EMS 2MODE CLKUP      520
3MODE CLKUP          517
2MODE                448
2MODE 2LKUP          383
EMS                  252
3MODE                166
CMODE                150
CMODE CLKUP          130
VMODE CLKUP          105
SIL Creeper           72
2LKUP                 63
DC/FW                 53
VLKUP                 52
EMS CLKUP             50
EMS 2MODE             46
6MODE CLKUP           41
4MODE                 35
VMODE VLKUP           26
2MODE 3LKUP           22
2MODE DC/FW           19
CMODE VLKUP           17
3LKUP                 15
EMS 3MODE             11
Overdrive             10
Lockup                 9
2MODE VLKUP            9
SIL EMS                7
6MODE                  6
SIL 3MODE              6
4MODE CLKUP            6
3MODE VLKUP            5
SIL 2MODE CLKUP        5
EMS 2MODE CLKU         5
Elec Overdrive         3
Mech Overdrive         3
EMS 3MODE CLKUP        3
SIL 3MODE CLKUP        2
LONG RATIO             2
VMODE                  2
EMS CMODE CLKUP        2
SIL CMODE              2
3MODE 2LKUP            2
2MODE CLKUP FW         2
3MODE CLKUP FW         1
EMS 5MODE              1
SIL CLKUP              1
fuel injection         1
Lockup A3              1
Name: trans_dscr_fna, dtype: int64

In [222]:
tb_veic_messy\
    .select_dtypes(include = "number")\
    .isna()

,Unnamed: 0,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,engId,feScore,fuelCost08,fuelCostA08,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,UCity,UCityA,UHighway,UHighwayA,youSaveSpend,charge240b,phevCity,phevHwy,phevComb,mfrCodeDffr,year_num,year_map,num_val_na
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37838,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
37839,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
37840,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
37841,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
37842,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [224]:
tb_veic_messy\
    .select_dtypes(include = "number")\
    .isna().sum(axis = 0)\
    .sort_values(ascending=False)

cylinders      123
displ          120
year_map         1
Unnamed: 0       0
rangeCity        0
              ...
fuelCost08       0
fuelCostA08      0
ghgScore         0
ghgScoreA        0
num_val_na       0
Length: 63, dtype: int64

In [225]:
tb_veic_messy['cylinders'].unique()

array([ 4., 12.,  8.,  6.,  5., 10.,  2.,  3., nan, 16.])

Podemos utilizar a média de uma coluna numérica como substituto para valores NAs. Essa técnica chama-se imputação de valores nulos, e, no módulo 3 veremos formas menos rudimentares de utiliza-la!

In [227]:
 tb_veic_messy['cylinders'].fillna(tb_veic_messy['cylinders'].mean())

0         4.0
1        12.0
2         4.0
3         8.0
4         4.0
         ...
37838     4.0
37839     4.0
37840     4.0
37841     4.0
37842     4.0
Name: cylinders, Length: 37843, dtype: float64

In [228]:
tb_veic_messy['cyl_impu'] = tb_veic_messy['cylinders'].fillna(tb_veic_messy['cylinders'].mean())
tb_veic_messy['cyl_impu'].unique()

array([ 4.        , 12.        ,  8.        ,  6.        ,  5.        ,
       10.        ,  2.        ,  3.        ,  5.73799046, 16.        ])

In [229]:
tb_veic_messy[['cyl_impu', 'cylinders']].describe()

           cyl_impu     cylinders
count  37843.000000  37720.000000
mean       5.737990      5.737990
std        1.748946      1.751795
min        2.000000      2.000000
25%        4.000000      4.000000
50%        6.000000      6.000000
75%        6.000000      6.000000
max       16.000000     16.000000

Devemos sempre tomar cuidado quando imputamos dados: as vezes podemos estar adicionando informações onde não devemos. Vamos investigar os carros com 0 cilindros diretamente:

In [230]:
tb_na_cyl = tb_veic_messy[tb_veic_messy['cylinders'].isna()]
tb_na_cyl.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 123 entries, 7138 to 30975
Data columns (total 91 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       123 non-null    int64
 1   barrels08        123 non-null    float64
 2   barrelsA08       123 non-null    float64
 3   charge120        123 non-null    float64
 4   charge240        123 non-null    float64
 5   city08           123 non-null    int64
 6   city08U          123 non-null    float64
 7   cityA08          123 non-null    int64
 8   cityA08U         123 non-null    float64
 9   cityCD           123 non-null    float64
 10  cityE            123 non-null    float64
 11  cityUF           123 non-null    float64
 12  co2              123 non-null    int64
 13  co2A             123 non-null    int64
 14  co2TailpipeAGpm  123 non-null    float64
 15  co2TailpipeGpm   123 non-null    float64
 16  comb08           123 non-null    int64
 17  comb08U          123 non-null    float64
 18  combA08          123 non-null    int64
 19  combA08U         123 non-null    float64
 20  combE            123 non-null    float64
 21  combinedCD       123 non-null    float64
 22  combinedUF       123 non-null    float64
 23  cylinders        0 non-null      float64
 24  displ            3 non-null      float64
 25  drive            115 non-null    object
 26  engId            123 non-null    int64
 27  eng_dscr         9 non-null      object
 28  feScore          123 non-null    int64
 29  fuelCost08       123 non-null    int64
 30  fuelCostA08      123 non-null    int64
 31  fuelType         123 non-null    object
 32  fuelType1        123 non-null    object
 33  ghgScore         123 non-null    int64
 34  ghgScoreA        123 non-null    int64
 35  highway08        123 non-null    int64
 36  highway08U       123 non-null    float64
 37  highwayA08       123 non-null    int64
 38  highwayA08U      123 non-null    float64
 39  highwayCD        123 non-null    float64
 40  highwayE         123 non-null    float64
 41  highwayUF        123 non-null    float64
 42  hlv              123 non-null    int64
 43  hpv              123 non-null    int64
 44  id               123 non-null    int64
 45  lv2              123 non-null    int64
 46  lv4              123 non-null    int64
 47  make             123 non-null    object
 48  model            123 non-null    object
 49  mpgData          123 non-null    object
 50  phevBlended      123 non-null    bool
 51  pv2              123 non-null    int64
 52  pv4              123 non-null    int64
 53  range            123 non-null    int64
 54  rangeCity        123 non-null    float64
 55  rangeCityA       123 non-null    float64
 56  rangeHwy         123 non-null    float64
 57  rangeHwyA        123 non-null    float64
 58  trany            114 non-null    object
 59  UCity            123 non-null    float64
 60  UCityA           123 non-null    float64
 61  UHighway         123 non-null    float64
 62  UHighwayA        123 non-null    float64
 63  VClass           123 non-null    object
 64  year             123 non-null    object
 65  youSaveSpend     123 non-null    int64
 66  guzzler          0 non-null      object
 67  trans_dscr       0 non-null      object
 68  tCharger         2 non-null      object
 69  sCharger         0 non-null      object
 70  atvType          120 non-null    object
 71  fuelType2        0 non-null      object
 72  rangeA           0 non-null      object
 73  evMotor          119 non-null    object
 74  mfrCode          94 non-null     object
 75  c240Dscr         37 non-null     object
 76  charge240b       123 non-null    float64
 77  c240bDscr        36 non-null     object
 78  createdOn        123 non-null    object
 79  modifiedOn       123 non-null    object
 80  startStop        120 non-null    object
 81  phevCity         123 non-null    int64
 82  phevHwy          123 non-null    int64
 83  phevComb         123 non-null    int64
 84  year_num_errado  123 non-null    object
 85  mfrCodeDffr      123 non-null    int64
 86  year_num         123 non-null    int64
 87  year_map         123 non-null    float64
 88  num_val_na       123 non-null    int64
 89  trans_dscr_fna   123 non-null    object
 90  cyl_impu         123 non-null    float64
dtypes: bool(1), float64(34), int64(30), object(26)
memory usage: 87.6+ KB

Agora vamos investigar se esses automóveis tem algum **atributo** que os diferencie:

In [231]:
tb_na_cyl.select_dtypes(include = 'object').describe()

,drive,eng_dscr,fuelType,fuelType1,make,model,mpgData,trany,VClass,year,guzzler,trans_dscr,tCharger,sCharger,atvType,fuelType2,rangeA,evMotor,mfrCode,c240Dscr,c240bDscr,createdOn,modifiedOn,startStop,year_num_errado,trans_dscr_fna
count,115,9,123,123,123,123,123,114,123,123,0,0,2,0,120,0,0,119,94,37,36,123,123,120,123,123
unique,5,3,2,2,23,58,2,3,15,16,0,0,1,0,1,0,0,57,15,5,4,37,33,1,18,1
top,Front-Wheel Drive,Lead Acid,Electricity,Electricity,Tesla,RAV4 EV,N,Automatic (A1),Large Cars,2016,NaN,NaN,T,NaN,EV,NaN,NaN,55 kW DCPM,TSL,standard charger,80 amp dual charger,Tue Jan 01 00:00:00 EST 2013,Fri Apr 11 00:00:00 EDT 2014,N,2016,OUTROS
freq,45,4,120,120,32,7,117,106,28,30,NaN,NaN,2,NaN,120,NaN,NaN,8,32,28,28,59,36,120,30,123

Carros elétricos não tem motores com cilindros! Nossa imputação está fundamentalmente errada. Como podemos corrigi-la, criando uma nova coluna de `cylinders` imputada?

In [ ]:
# DESAFIO

In [239]:
tb_veic_messy.corr().melt()

/var/folders/c2/4vv1dtt97gl9bn1lvw8rf0k40000gn/T/ipykernel_44873/3951577228.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  tb_veic_messy.corr().melt()

        variable     value
0     Unnamed: 0  1.000000
1     Unnamed: 0 -0.066304
2     Unnamed: 0  0.041524
3     Unnamed: 0       NaN
4     Unnamed: 0  0.046506
...          ...       ...
4220    cyl_impu       NaN
4221    cyl_impu  0.100298
4222    cyl_impu  0.100264
4223    cyl_impu -0.164516
4224    cyl_impu  1.000000

[4225 rows x 2 columns]

## Duplicação de linhas

Em algumas situações, nossos DataFrames podem conter linas duplicadas. Para duplicações simples (onde todas as colunas são iguais) podemos utilizar o método `.duplicated()` para limpar as duplicatas.

In [232]:
frutas = pd.DataFrame({
    'fruta':['laranja', 'laranja', 'mamão', 'laranja'],
    'cidade':['Rio de Janeiro', 'Atibaia', 'Campinas', 'Rio de Janeiro']
})

In [233]:
frutas

     fruta          cidade
0  laranja  Rio de Janeiro
1  laranja         Atibaia
2    mamão        Campinas
3  laranja  Rio de Janeiro

In [237]:
frutas.duplicated()

0    False
1    False
2    False
3     True
dtype: bool

In [235]:
frutas.loc[~frutas.duplicated(),]

     fruta          cidade
0  laranja  Rio de Janeiro
1  laranja         Atibaia
2    mamão        Campinas

# Voltamos 21h45!